CrateConfig_Sections:
- MOTR_CONFIG
- WORKLOAD_SPEC
MOTR_CONFIG:
  MOTR_LOCAL_ADDR: 192.168.0.95@tcp:12345:4:1
  MOTR_HA_ADDR: 192.168.0.95@tcp:12345:1:1
  PROF: 0x7000000000000001:0x2c
  PROCESS_FID: 0x7200000000000001:0x26
  LAYOUT_ID: 4
  IS_OOSTORE: 1
  IS_READ_VERIFY: 0
  TM_RECV_QUEUE_MIN_LEN: 16
  MAX_RPC_MSG_SIZE: 262144
  IDX_SERVICE_ID: 1
  ADDB_INIT: 1
WORKLOAD_SPEC:
- WORKLOAD:
    WORKLOAD_TYPE: 1
    WORKLOAD_SEED: tstamp
    OPCODE: 5
    STARTING_OBJ_ID: '30:30'
    IOSIZE: 10m
    BLOCK_SIZE: 8k
    BLOCKS_PER_OP: 2
    RAND_IO: 0
    MAX_NR_OPS: 1
    NR_OBJS: 5
    NR_THREADS: 5
    MODE: 1
    THREAD_OPS: 0
    NR_ROUNDS: 2
    EXEC_TIME: unlimited
    SOURCE_FILE: /tmp/128M
    LOG_LEVEL: 2
