test_14921:
    batch:
    - cmnd: m0kv
      params: 'index create "4:5"'
    - cmnd: m0kv
      params: 'index put "4:5" "key1" "val1" -s'
    - cmnd: m0kv
      params: 'index get "4:5" "key1"  -s'
    - cmnd: m0kv
      params: 'index list "4:5" 2'
    - cmnd: m0kv
      params: '-s index del "4:5" "key1" '
test_23198:
    batch:
    - cmnd: m0kv
      params: 'index genf 5 fid.txt'
    - cmnd: cat
      params: 'fid.txt'
    - cmnd: rm
      params: 'fid.txt'
test_23199:
    batch:
    - cmnd: m0kv
      params: 'index genf 5 fid.txt'
    - cmnd: cat
      params: 'fid.txt'
    - cmnd: m0kv
      params: 'index create ''780000000000000a:1'''
    - cmnd: m0kv
      params: 'index drop ''780000000000000a:1'''
    - cmnd: rm
      params: 'fid.txt'
test_23200:
    batch:
    - cmnd: m0kv
      params: 'index genf 5 /tmp/fid.txt'
    - cmnd: cat
      params: '/tmp/fid.txt'
    - cmnd: m0kv
      params: 'index create @/tmp/fid.txt'
    - cmnd: m0kv
      params: 'index list "780000000000000a:2" 2'
    - cmnd: m0kv
      params: 'index drop @/tmp/fid.txt'
    - cmnd: rm
      params: '/tmp/fid.txt'
test_23202:
    batch:
    - cmnd: m0kv
      params: 'index genf 5 fid3.txt'
    - cmnd: cat
      params: 'fid3.txt'
    - cmnd: m0kv
      params: 'index create @fid3.txt'
    - cmnd: m0kv
      params: 'index lookup ''@fid3.txt'''
    - cmnd: m0kv
      params: 'index drop @fid3.txt'
    - cmnd: rm
      params: 'fid3.txt'
test_23203:
    batch:
    - cmnd: m0kv
      params: 'index genf 5 fid3.txt'
    - cmnd: cat
      params: 'fid3.txt'
    - cmnd: m0kv
      params: 'index create ''780000000000000a:2'''
    - cmnd: m0kv
      params: 'index drop ''780000000000000a:2'''
    - cmnd: rm
      params: 'fid3.txt'