CrateConfig_Sections:
- MOTR_CONFIG
- WORKLOAD_SPEC
MOTR_CONFIG:
  MOTR_LOCAL_ADDR: 192.168.79.53@o2ib:12345:4:1
  MOTR_HA_ADDR: 192.168.79.53@o2ib:12345:1:1
  PROF: 0x7000000000000001:0x19a
  PROCESS_FID: 0x7200000000000001:0x5c
  LAYOUT_ID: 4
  IS_OOSTORE: 1
  IS_READ_VERIFY: 0
  TM_RECV_QUEUE_MIN_LEN: 16
  MAX_RPC_MSG_SIZE: 262144
  IDX_SERVICE_ID: 1
  ADDB_INIT: 1
WORKLOAD_SPEC:
- WORKLOAD:
    WORKLOAD_TYPE: 1
    WORKLOAD_SEED: tstamp
    OPCODE: 3
    IOSIZE: 1g
    BLOCK_SIZE: 128m
    BLOCKS_PER_OP: 1
    RAND_IO: 1
    MAX_NR_OPS: 1
    NR_OBJS: 10
    NR_THREADS: 10
    MODE: 1
    THREAD_OPS: 0
    NR_ROUNDS: 1
    EXEC_TIME: unlimited
    SOURCE_FILE: /tmp/128M
    LOG_LEVEL: 3
