motr:
  MOTR_LOCAL_ADDR: 192.168.0.95@tcp:12345:4:1
  MOTR_HA_ADDR: 192.168.0.95@tcp:12345:1:1
  PROF: 0x7000000000000001:0x2c
  PROCESS_FID: 0x7200000000000001:0x26
  LAYOUT_ID: 4
  IS_OOSTORE: 1
  IS_READ_VERIFY: 0
  TM_RECV_QUEUE_MIN_LEN: 16
  MAX_RPC_MSG_SIZE: 262144
  IDX_SERVICE_ID: 1
  ADDB_INIT: 1
mode:
  cluster:
    app: hare
    cdf: /var/lib/hare/cluster.yaml
    client_index: 1
  singlenode:
    config_file: /etc/motr/conf.xc
    base_port: 200
sandbox_dir: /tmp/sandbox
timeout: 120
workloads:
  test_14882:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/input bs=4k count=786'
      config_overrides: null
      timeout: 100
    - cmnd: m0cp
      params: '-s 4k -c 786 -o 10:11 /tmp/input'
      config_overrides: null
      timeout: 100
    - cmnd: m0trunc
      params: '-s 4k -c 512 -t 256 -o 10:11'
      config_overrides: null
      timeout: null
    - cmnd: m0cat
      params: '-s 4k -c 256 -o 10:11 > /tmp/output1'
      config_overrides: null
      timeout: 120
    - cmnd: m0cat
      params: '-s 4k -c 256 -o 10:11 > /tmp/output2'
      config_overrides: null
      timeout: 120
    - cmnd: diff
      params: '/tmp/output1 /tmp/output2'
      config_overrides: null
      timeout: null
    - cmnd: md5sum
      params: '/tmp/output1 /tmp/output2'
      config_overrides: null
      timeout: null
    - cmnd: du
      params: '-h  /tmp/input'
      config_overrides: null
      timeout: null
    - cmnd: du
      params: '-h  /tmp/output1'
      config_overrides: null
      timeout: null
    - cmnd: du
      params: '-h  /tmp/output2'
      config_overrides: null
      timeout: null
    - cmnd: m0unlink
      params: '-o 10:11'
      config_overrides: null
      timeout: null
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/128M bs=1M count=128'
      config_overrides: null
      timeout: 100
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_14882_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/input /tmp/output /tmp/128M'
      config_overrides: null
      timeout: null
    runs: 1
  test_14921:
    batch:
    - cmnd: m0kv
      params: 'index create "4:5"'
      config_overrides: null
      timeout: 100
    - cmnd: m0kv
      params: 'index put "4:5" "key1" "val1" -s'
      config_overrides: null
      timeout: 100
    - cmnd: m0kv
      params: 'index get "4:5" "key1"  -s'
      config_overrides: null
      timeout: 100
    - cmnd: m0kv
      params: 'index list "4:5" 2'
      config_overrides: null
      timeout: 100
    - cmnd: m0kv
      params: '-s index del "4:5" "key1" '
      config_overrides: null
      timeout: 200
    runs: 1
  test_14922:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/var/motr/2G bs=1M count=2048'
      config_overrides: null
      timeout: null
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_14922_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /var/motr/2G'
      config_overrides: null
      timeout: null
    runs: 1
  test_14923:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/var/motr/2G bs=1M count=2048'
      config_overrides: null
      timeout: null
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_14923_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /var/motr/2G'
      config_overrides: null
      timeout: null
    runs: 1
  test_14924:
    batch:
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_14924_file1.yaml'
      config_overrides: null
      timeout: null
    runs: 1
  test_14925:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/var/motr/2G bs=1M count=2048'
      config_overrides: null
      timeout: null
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_14925_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_14925_file2.yaml'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /var/motr/2G'
      config_overrides: null
      timeout: null
    runs: 1
  test_14926:
    batch:
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_14926_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_14926_file2.yaml'
      config_overrides: null
      timeout: null
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_14926_file3.yaml'
      config_overrides: null
      timeout: null
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_14926_file4.yaml'
      config_overrides: null
      timeout: null
    runs: 1
  test_22939:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/128M bs=1M count=128'
      config_overrides: null
      timeout: 100
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_22939_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/128M'
      config_overrides: null
      timeout: null
    runs: 1
  test_22954:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/128M bs=1M count=128'
      config_overrides: null
      timeout: 100
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_22954_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/128M'
      config_overrides: null
      timeout: null
    runs: 1
  test_23191:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/128M bs=1M count=128'
      config_overrides: null
      timeout: 100
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_23191_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/128M'
      config_overrides: null
      timeout: null
    runs: 1
  test_23192:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/128M bs=1M count=128'
      config_overrides: null
      timeout: 100
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_23192_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/128M'
      config_overrides: null
      timeout: null
    runs: 1
  test_23193:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/128M bs=1M count=128'
      config_overrides: null
      timeout: 100
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_23193_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/128M'
      config_overrides: null
      timeout: null
    runs: 1
  test_23194:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/128M bs=1M count=128'
      config_overrides: null
      timeout: 100
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_23194_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/128M'
      config_overrides: null
      timeout: null
    runs: 1
  test_23195:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/128M bs=1M count=128'
      config_overrides: null
      timeout: 100
    - cmnd: m0crate
      params: '-S m0crate_workload_batch_test_23195_file1.yaml'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/128M'
      config_overrides: null
      timeout: null
    runs: 1
  test_23196:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/input bs=4k count=1024'
      config_overrides: null
      timeout: null
    - cmnd: m0cp
      params: '-s 4096 -c 1024 -o 10:20  /tmp/input'
      config_overrides: null
      timeout: null
    - cmnd: m0cat
      params: '-s 4096 -c 1024 -o 10:20 > /tmp/output'
      config_overrides: null
      timeout: null
    - cmnd: m0unlink
      params: '-o 10:20'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/input /tmp/output'
      config_overrides: null
      timeout: null
    runs: 1
  test_23197:
    batch:
    - cmnd: dd
      params: 'if=/var/log/messages bs=4k count=10 of=/tmp/samplelogs.txt'
      config_overrides: null
      timeout: null
    - cmnd: m0cp
      params: '-s 4k -c 10 -o 02:98  /tmp/samplelogs.txt'
      config_overrides: null
      timeout: null
    - cmnd: m0cat
      params: '-s 4k -c 10 -o 02:98 > /tmp/test1.txt'
      config_overrides: null
      timeout: null
    - cmnd: diff
      params: '/tmp/samplelogs.txt /tmp/test1.txt'
      config_overrides: null
      timeout: null
    - cmnd: md5sum
      params: '/tmp/samplelogs.txt /tmp/test1.txt'
      config_overrides: null
      timeout: null
    - cmnd: m0unlink
      params: '-o 02:98'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/samplelogs.txt /tmp/test1.txt'
      config_overrides: null
      timeout: null
    runs: 1
  test_23198:
    batch:
    - cmnd: m0kv
      params: 'index genf 5 fid.txt'
      config_overrides: null
      timeout: null
    - cmnd: cat
      params: 'fid.txt'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: 'fid.txt'
      config_overrides: null
      timeout: null
    runs: 1
  test_23199:
    batch:
    - cmnd: m0kv
      params: 'index genf 5 fid.txt'
      config_overrides: null
      timeout: null
    - cmnd: cat
      params: 'fid.txt'
      config_overrides: null
      timeout: null
    - cmnd: m0kv
      params: 'index create ''780000000000000a:1'''
      config_overrides: null
      timeout: null
    - cmnd: m0kv
      params: 'index drop ''780000000000000a:1'''
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: 'fid.txt'
      config_overrides: null
      timeout: null
    runs: 1
  test_23200:
    batch:
    - cmnd: m0kv
      params: 'index genf 5 /tmp/fid.txt'
      config_overrides: null
      timeout: null
    - cmnd: cat
      params: '/tmp/fid.txt'
      config_overrides: null
      timeout: null
    - cmnd: m0kv
      params: 'index create @/tmp/fid.txt'
      config_overrides: null
      timeout: null
    - cmnd: m0kv
      params: 'index list "780000000000000a:2" 2'
      config_overrides: null
      timeout: null
    - cmnd: m0kv
      params: 'index drop @/tmp/fid.txt'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '/tmp/fid.txt'
      config_overrides: null
      timeout: null
    runs: 1
  test_23202:
    batch:
    - cmnd: m0kv
      params: 'index genf 5 fid3.txt'
      config_overrides: null
      timeout: null
    - cmnd: cat
      params: 'fid3.txt'
      config_overrides: null
      timeout: null
    - cmnd: m0kv
      params: 'index create @fid3.txt'
      config_overrides: null
      timeout: null
    - cmnd: m0kv
      params: 'index lookup ''@fid3.txt'''
      config_overrides: null
      timeout: null
    - cmnd: m0kv
      params: 'index drop @fid3.txt'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: 'fid3.txt'
      config_overrides: null
      timeout: null
    runs: 1
  test_23203:
    batch:
    - cmnd: m0kv
      params: 'index genf 5 fid3.txt'
      config_overrides: null
      timeout: null
    - cmnd: cat
      params: 'fid3.txt'
      config_overrides: null
      timeout: null
    - cmnd: m0kv
      params: 'index create ''780000000000000a:2'''
      config_overrides: null
      timeout: null
    - cmnd: m0kv
      params: 'index drop ''780000000000000a:2'''
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: 'fid3.txt'
      config_overrides: null
      timeout: null
    runs: 1
  test_14954:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/input bs=4k count=786'
      config_overrides: null
      timeout: null
    - cmnd: m0cp
      params: '-s 4k -c 768 -o 13:11  /tmp/input'
      config_overrides: null
      timeout: null
    - cmnd: m0cat
      params: '-s 4k -c 512 -o 13:11 > /tmp/output1'
      config_overrides: null
      timeout: null
    - cmnd: m0trunc
      params: '-s 4k -c 512 -t 256 -o 13:11'
      config_overrides: null
      timeout: null
    - cmnd: m0cat
      params: '-s 4k -c 512 -o 13:11 > /tmp/output2'
      config_overrides: null
      timeout: null
    - cmnd: diff
      params: '/tmp/output1 /tmp/output2'
      config_overrides: null
      timeout: null
    - cmnd: du
      params: '-h /tmp/input'
      config_overrides: null
      timeout: null
    - cmnd: du
      params: '-h /tmp/output1'
      config_overrides: null
      timeout: null
    - cmnd: du
      params: '-h /tmp/output2'
      config_overrides: null
      timeout: null
    - cmnd: m0unlink
      params: '-o 13:11'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/input /tmp/output'
      config_overrides: null
      timeout: null
    runs: 1
  test_23205:
    batch:
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/input bs=4096 count=1024'
      config_overrides: null
      timeout: null
    - cmnd: m0cp
      params: '-s 4k -c 1k -o 01:02  /tmp/input'
      config_overrides: null
      timeout: null
    - cmnd: m0unlink
      params: '-o 01:02'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/input'
      config_overrides: null
      timeout: null
    runs: 1
  test_23207:
    batch:
    - cmnd: m0touch
      params: '-o 10:20:00'
      config_overrides: null
      timeout: null
    - cmnd: dd
      params: 'if=/dev/urandom of=/tmp/input bs=4096 count=1024'
      config_overrides: null
      timeout: null
    - cmnd: m0cp
      params: '-s 4k -c 1k -o 10:20:00  /tmp/input  -u'
      config_overrides: null
      timeout: null
    - cmnd: m0unlink
      params: '-o 10:20:00'
      config_overrides: null
      timeout: null
    - cmnd: rm
      params: '-f /tmp/input'
      config_overrides: null
      timeout: null
    runs: 1
