s3_params:
  password: "oOPdW3a5sMcVfchrdiJGDSIrIu49ByTsprb/jIQbowU="
  new_password: "udXC/QLVeEgI0yIidEGy5XlwitDX6rLezfUlJ39i7zU="

test_configs:
  test_9784:
    password: "aNOm4xqgBspLAC4o9dR704Ti7yoOGZ/15JzLw1Jb36A="

  test_9785:
    password: "IEhPX0D4Ek79B3tYce+ZfwICAj51DLmbTiyEP3aSJs00E3BcvVKHqeJn0Rm6/vwfISaGJOJRPZB7axzfgYNTZju8gHo9FFl7f/x1aeQHHRR+7z8MBZr3dMy7zhBVW6FtuMbA0S/I5ASZgeEgwL5jy4PBL52mw9AQ46T4ZApXL45Cjg1LiN5Ul8unpGdp/RS5ViowWWbjFfnx11YvuRprxg=="

  test_9786:
    list_of_passwords:
      - "Lqckb7sMfSw7joS2zFn2LZK1RlMUx01FHVMoWVEFhDU="
      - "COmpsDmylsDZ7iLC9jv78ZI+l0bUpo/TwNMhsfrMC00="
      - "oOPdW3a5sMcVfchrdiJGDSIrIu49ByTsprb/jIQbowU="
      - "2Ugu1j2T3vpGDQKe7IKP39bcVtf3JWkrtUl3oPVvI8U="

  test_9787:
    list_special_invalid_char:
      - "SyKP0sW5djTj5mvAfwUNZdG6pQgm5vN7ytfD+xwfoqs="
      - "Dn3yl1ldWmjiB4XlcUJiENeUgZuCiz0xMGB945CxUk0="
      - "fj1Jnp+tnzDaiNugjqy6QmH3finqsjhCYrDvUcfP8fI="
      - "O36j7i6uMDNpWUs086czDzdEYNmgJiuvxpFbtXrt4+U="
      - "p/MwB+c2Y10T5ISQfDcR/XxSXJ+I664xJnOIV0KD14k="
      - "uLXhYl8AyPjiB+x7I+GPuCt8ygIwXEBCzdcM33xF7I8="

  test_9812:
    new_password: "Sf7bfyuMGqCDb7yoxB8COo9dbkk1LiFEB5KTsYvNv9s="

  test_9820:
    new_password: "nCuTjXVKVqZA9ARDwKbCYhenkXC/JCPT11Qi483PpNA="

  test_9822:
    new_password: "KogDN0tQA0UMf4aQClKmHFV4Pk0tkIOY9sgeOWlI3jk="

  test_9866:
    password: "nRHRiP0c8Uf7tPaDgAuR7V4Po1XLAG61KBfOpR3dnsI="

  test_9870:
    invalid_password: "hBnypgcZpgCgs12vxVP+IgaUKdfbkHWrCwq3M5ueZpM="

  test_9871:
    user_password: "ND0e3stzCIBPKbh2Z26+cmfVnhrbl2n9t2kfKrgX6FM="

  test_9875:
    user_password: "f8dpfmqXLqaeCB0We0C2ueVKbun6JZecL5FWpX+1iLY="

  test_9824:
    password: "pHn3CxMXukvTVsrRtuXLZJYZ456P7GPqbJ9pXuqnnwA="
    new_password: "xjaSUo4RN1hzWjtRxbQD1QEG5kRKc+68E+Dj7PR16Nk="

  test_9825:
    password: "p/oNeZU22mOz0HEvhDBfDzQneAEayCTE+A2fzbzcOIU="

  test_9826:
    password: "IF3OQHWNXva4PJRak+mDiXyysjuH0RdZSHde8L2T8js="
    new_password: "o22+WkHq9tJVUUZd21qKzHBM9wk+Fi/3QaUsDPcIzIM="

  test_9828:
    password: "r228j6/9zt6jRPmzNfEQ+QckfmEQfmFNrUgyyGeNNjs="
    new_password: "kIBdqNjdRrmF21KRTJEsuH+1ioZk71NfxB1sxdc264zb5vfdVkH5HFKMu3IDWcfVe1HY3rinkmLCJWeAPgTx2CUjr6x8J8dByHSgaxamGLzUPbEnt0k6k1zvJuM/9R8P+cHUkxqnHh8AZiF5mNgvyjvPQqo2VejNlsIOMpmex9Sj+de41t0uIlrfE3RhU0tB9ttgCOEVRnlDhJzJB1dXdA=="

  test_9829:
    password: "AI/FSXlSY23YVxh09sMDXONClvgKk89Ch5n0KouV5o4="
    new_password: "PomcbXwbbhnSGcLSBMb3LFUloFpEiSeM+V+92dJtU+DYvl8pCcIyNo4fjt4mliK1wKNiNotvTRq2qKtEqPl/8bPVH2IalqVa68+8dHj6xGpx4yo8nw1udQapZs7npiPO70SxOdKJafzl8DBivozVUfC/XZ0xiFy1aWDICOiSQpjOKYMXEUAV52yzYSTK7ugVpTOz0vR7Twn7jssrFtun6g=="

  test_9830:
    password: "ypgWOkqNNsVscOWu82nVRHTFZESIMk1DKT3lQLVWFLk="
    new_password: "+GEMUYEz6+bFdclu/kd79rg8qh2//9Z0V1DnqCHiXzg="

  test_9831:
    password: "a9QLKFuCAcyQDKJvA4H3SbHhybUk/7DU2uXvzr6p9sk="

  test_9832:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
    special_char_pwd:
      - "9i0YFGVrSRCkWbFRdtcEqEqH93UfdEbZ1hG2ddaKDnU="
      - "AIGL/7QSRnIblF+CxTNxaXcD5lm6YvpmuwWEn9i7+aw="
      - "hOkcMENfHOqUUgNxmF8XvybRA3g86uHkNqm9YGD1g7I="
      - "O9l0stg5O7l2e4fLUadEoGrK5ZxAm18CDkv5b+te0fE="
      - "MFQ8yor+DGx+4ofiVjY4uTVIOLSfrQqujElzeXYOqHw="
      - "Sgb35cICs1Di02XxTxcWnv/e7HxUVQDlVLVecCAntG0="

  test_9833:
    password: "8pPkYatDx8p747rMmEetKY8bNy9/FP1yskp2uWu7Enw="
    new_password: "3yJbrKV8wBX6jH1OauovEb2WpAr9G2dNUKm41i9rum0="

  test_9834:
    password: "3JM1hp8xFmN1D2mQJtOYCSKp/uJtpIwu7hJzMEI0UTc="
    new_password: "DLzaqFOr0UOgOKrWI3P3XqNuTvF2i1Kq+kSgKF3w5AQ="

  test_9835:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="

  test_9836:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="

  test_9837:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="

  test_9838:
    password: "o22+WkHq9tJVUUZd21qKzHBM9wk+Fi/3QaUsDPcIzIM="

  test_9840:
    password: "4XIWHPsV9dmVs8u1CLGftbQ7fhIK2zh0sZpjAf+hNF2mzpN6cKZ53asTf0IG3HUina6WrTV/+CEnEQs6wpws+LIXc6ZSpZdNx69pX+BLswdqnznirnoePDqyEgYPR8nxhCL74kyM+oAOGi/pgbGThfllnAiVjOUBbNNmWXJ+wJplhZQATanJ6R0W8MZxlYBeXuGxEYL3J6dSaycoRfOinQ=="

  test_9841:
    password: "CwCrXx838o3H58net0yeCg/jJgOS4OLsEhAUu6LlVpB9/Sq0wwsg82cSnXQk8MfmhKjhnYRR2dQz893JNZG66G0/3xPWk7s72miXYDxIoQEM7zQ1D0w+t/+4xAjpw8viwUo9Ls5gRax+4IGNsIEwhD6Te073tr6an/s4iuhnfsDh3xHSvBSr8qkc8na8e0VDhZmcsS9T8rA/uydXMQ470Q=="

  test_9842:
    password: "vhiTxsPCQUtEyW2imNVg8iYrgbA73G/RONETSw7i3tM="

  test_9843:
    special_char_pwd:
      - "xZ4MvdpVZchbVOZASxVv9k4iqC6vVs5eE7eUf4FIXZw="
      - "LvnCPJgnbHybOy++aQqnAYm+xMEYK0Rv5WihCTRdbDc="
      - "SWCB7uQ3sCsHdSWYHvRzvWbQaRtCSe3PkvKd2dOVqQ0="
      - "OjSOg11x7jqYFCV4oIaPWG2Xp+qRWGHV+d0KjGZpoIE="
      - "xQCBE/BWer4HeYWU+m1IShXRkHIjEv9PBq3z3v3f2i4="
      - "CxD7a9fqP4y+f9c7kC4ahb1EzfsBHIwpl7bKfj8HCeY="
    password_reset: True

  test_9844:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="

  test_9845:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="

  test_9846:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="

  test_9847:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="

  test_9848:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="

  test_9849:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="

  test_9876:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
    new_password: "DLzaqFOr0UOgOKrWI3P3XqNuTvF2i1Kq+kSgKF3w5AQ="

  test_9877:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
    new_password: "DLzaqFOr0UOgOKrWI3P3XqNuTvF2i1Kq+kSgKF3w5AQ="

  test_9878:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
    new_password: "DLzaqFOr0UOgOKrWI3P3XqNuTvF2i1Kq+kSgKF3w5AQ="

  test_9879:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
    new_password: "l8eFHwZQtUp++zFTdUEwnVNeMev7oSIy3t8wXyTcDWw="

  test_9880:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
    new_password: "4XIWHPsV9dmVs8u1CLGftbQ7fhIK2zh0sZpjAf+hNF2mzpN6cKZ53asTf0IG3HUina6WrTV/+CEnEQs6wpws+LIXc6ZSpZdNx69pX+BLswdqnznirnoePDqyEgYPR8nxhCL74kyM+oAOGi/pgbGThfllnAiVjOUBbNNmWXJ+wJplhZQATanJ6R0W8MZxlYBeXuGxEYL3J6dSaycoRfOinQ=="

  test_9881:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
    new_password: "CwCrXx838o3H58net0yeCg/jJgOS4OLsEhAUu6LlVpB9/Sq0wwsg82cSnXQk8MfmhKjhnYRR2dQz893JNZG66G0/3xPWk7s72miXYDxIoQEM7zQ1D0w+t/+4xAjpw8viwUo9Ls5gRax+4IGNsIEwhD6Te073tr6an/s4iuhnfsDh3xHSvBSr8qkc8na8e0VDhZmcsS9T8rA/uydXMQ470Q=="

  test_9882:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
    list_special_char_pwd:
      - "xZ4MvdpVZchbVOZASxVv9k4iqC6vVs5eE7eUf4FIXZw="
      - 'mCrRjCVmw8QDvfgohmP/S8Xfovbdq8S2JXdKXgcHs+g='
      - '++cmX3GLURLzQ+TVCG6FittvTMXbWMrj+H1hIqZIBPc='
      - "xQCBE/BWer4HeYWU+m1IShXRkHIjEv9PBq3z3v3f2i4="
      - "F3n+Q8yWcvdYMpZSdgaWuQhY3tsDPx+tM/RFZJXdFmk="
      - 'su5ibVDRAwBFfnNkr5guXAWdcfLOnuNPC4fAUbmjH10='
      - "GGVIMnuo60BI5fBgalcLe6MFCPxqIKQgHSx1R1G8eTY="
      - "P4dpkPtLAcswLMN+f1OnLUgECQX6QPOiiYtJXBzE1Fs="
      - 'biRcbHB3Xa8JsBzvaU9Rnd+Qgzd5e8kDw0J/i+tREZY='
      - "0Wzknj2AVsNR6ZgtWGpW/GPNjTVSLqlGkaayZmLuD3w="
      - "s2DAJ53F3TcdA2qZXxPB0ThvBcS7/ZhXrvEhDaxb+k4="
      - "zs7bwHv/tXAeIud2ULjeJuOqHEEwUAv5DJEWDWICObo="

  test_9883:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="

  test_9884:
    password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
    new_password: "U7UQ7NoFYowF5pqxRl5UzHFkrySVkfWI7pQL4nd+uQ0="

  test_9923:
    account_password: "DRU9Oz1HtTY5hkRuJrc0WtCpClN8v+ZfcgAckKTqnq0="
    user_password:  "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="

  test_9924:
    user_password: "AZayKOusURwffmkBDmZS9oQ6Q3V1XAIJ+BL6dYp49WI="

  test_9925:
    user_password: "AZayKOusURwffmkBDmZS9oQ6Q3V1XAIJ+BL6dYp49WI="

  test_9927:
    user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="

  test_9928:
    user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="

  test_9929:
    user_password: "AZayKOusURwffmkBDmZS9oQ6Q3V1XAIJ+BL6dYp49WI="

  test_9930:
    user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="

  test_9931:
    user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="

  test_9932:
    user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="

  test_9936:
    user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="
