test_1:
  TEST_ID: TEST-36594
  object_size:
    start: 0Kb
    end: 100Kb
  result_duration: 2h
  sessions_per_node: 1
  range_read: 100bytes
  tool: s3api
  operation: copy_object_range_read

 test_2:
   TEST_ID: TEST-36595
   object_size:
     start: 100Kb
     end: 1Mb
   result_duration: 2h
   sessions_per_node: 2
   range_read: 200bytes
   tool: s3api
   operation: copy_object_range_read

 test_3:
   TEST_ID: TEST-36596
   object_size:
     start: 1Mb
     end: 10Mb
   result_duration: 20h
   sessions_per_node: 3
   range_read: 500bytes
   tool: s3api
   operation: copy_object_range_read

 test_4:
   TEST_ID: TEST-36598
   object_size:
     start: 10Mb
     end: 20Mb
   result_duration: 1d
   sessions_per_node: 5
   range_read: 1000bytes
   tool: s3api
   operation: copy_object_range_read

 test_5:
   TEST_ID: TEST-36599
   object_size:
     start: 20Mb
     end: 100Mb
   result_duration: 1d
   sessions_per_node: 8
   range_read: 10Kb
   tool: s3api
   operation: copy_object_range_read

 test_6:
   TEST_ID: TEST-36600
   object_size:
     start: 100Mb
     end: 500Mb
   result_duration: 2d
   sessions_per_node: 13
   range_read: 100Kb
   tool: s3api
   operation: copy_object_range_read

 test_7:
   TEST_ID: TEST-36601
   object_size:
     start: 500Mb
     end: 1Gb
   result_duration: 2d
   sessions_per_node: 21
   range_read: 1Mb
   tool: s3api
   operation: copy_object_range_read

 test_8:
   TEST_ID: TEST-36602
   object_size:
     start: 1Gb
     end: 2Gb
   result_duration: 4d
   sessions_per_node: 34
   range_read: 10Mb
   tool: s3api
   operation: copy_object_range_read

 test_9:
   TEST_ID: TEST-36603
   object_size:
     start: 2Gb
     end: 5Gb
   result_duration: 5d
   sessions_per_node: 55
   range_read: 100Mb
   tool: s3api
   operation: copy_object_range_read

 test_10:
   TEST_ID: TEST-36604
   object_size:
     start: 5Gb
     end: 10Gb
   result_duration: 5d
   sessions_per_node: 89
   range_read: 150Mb
   tool: s3api
   operation: copy_object_range_read

 test_11:
   TEST_ID: TEST-36605
   object_size:
     start: 10Gb
     end: 20Gb
   result_duration: 5d
   sessions_per_node: 144
   range_read: 200Mb
   tool: s3api
   operation: copy_object_range_read

 test_12:
   TEST_ID: TEST-36607
   object_size:
     start: 20Gb
     end: 50Gb
   result_duration: 5d
   sessions_per_node: 233
   range_read: 1Gb
   tool: s3api
   operation: copy_object_range_read
