audit_logs:
    name_prefix: "audit"  # Used in cleanup ops for both bucket and account
    local_path: "/root/s3config.yaml"
    section: "S3_SERVER_CONFIG"
    key: "S3_AUDIT_LOGGER_POLICY"
    folder: "audit"
    file: "audit.log"
    pwd: "password"

test_5248:
    bucket_name: "audit-bkt5248"
    value: "disabled"

test_5236:
    bucket_name: "audit-bkt5236"
    object_name: "audit-obj5236"
    value: "syslog"
    file_size: 200
    total_parts: 4

test_5235:
    bucket_name: "audit-bkt5235"
    object_name: "audit-obj5235"
    file_size: 5
    value: "syslog"

test_5231:
    bucket_name: "audit-bkt5231"
    value: "syslog"

test_5213:
    bucket_name: "audit-bkt5213"
    object_name: "audit-obj5213"
    value: "log4cxx"
    file_size: 200
    total_parts: 4

test_5228:
    bucket_name: "audit-bkt5228"
    object_name: "audit-obj5228"
    file_size: 5
    value: "log4cxx"

test_5209:
    bucket_name: "audit-bkt5209"
    value: "log4cxx"

test_6253:
    bucket_name: "audit-bkt6253"
    value: "log4cxx"

test_6255:
    bucket_name: "audit-bkt6255"
    obj_name: "audit-obj6255"
    obj_size: 2
    value: "log4cxx"

test_5238:
    bucket_name: "audit-bkt5238"
    value: "syslog"

test_5240:
    bucket_name: "audit-bkt5240"
    obj_name: "audit-obj5240"
    obj_size: 5
    value: "syslog"

test_5246:
    bucket_name: "audit-bkt5246"
    object_name: "audit-obj5246"
    value: "syslog"
    file_size: 200
    total_parts: 4
