object_metadata:
  bkt_name_prefix: "obj-metadata"
  file_path: "/home/obj_metadata.txt"
  folder_path: "/home/metadata"
  mb_count: 5
test_8543:
  bucket_name: "obj-metadata8543"
  obj_name: "TestObj8543"
test_8544:
  bucket_name: "obj-metadata8544"
  obj_name: "!-_.*'()"
test_8545:
  bucket_name: "obj-metadata8545"
  obj_name: "tets!-_.obj*'(8545)"
test_8546:
  bucket_name: "obj-metadata8546"
  obj_name: "testobj8546"
  new_file_path: "/home/new_objmetadata.txt"
  key: "testkey"
  value: "testvalue"
test_8547:
  bucket_name: "obj-metadata8547"
  obj_key_length: 1024
test_8549:
  bucket_name: "obj-metadata8549"
  obj_name: "432165"
test_8550:
  bucket_name: "obj-metadata8550"
  start_range: 1025
  stop_range: 2000
  error_message: "KeyTooLongError"
test_8551:
  bucket_name: "obj-metadata8551"
  obj_name: "my_obj/abc_obj/def_obj"
test_8552:
  bucket_name: "obj-metadata8552"
  obj_list:
    - "test$obj"
    - "test@obj"
    - "test=obj"
    - "test;obj"
    - "test:obj"
    - "test+obj"
    - "test,obj"
    - "test?obj"
test_8553:
  bucket_name: "obj-metadata8553"
  obj_list:
    - "test_obj"
    - "test{obj"
    - "test^obj"
    - "test%obj"
    - "test~obj"
    - "test>obj"
    - "test#obj"
    - "test|obj"
    - "test}obj"
    - "test`obj"
    - "test]obj"
    - "test[obj"
test_8554:
  bucket_name: "obj-metadata8554"
  obj_name: "testobj8554"
  key: "key8554"
  value: "value8554"
test_8555:
  bucket_name: "obj-metadata8555"
  obj_name: "testobj8555"
  key: "key8555"
  value: "value8555"
  new_file_path: "/home/new_objmetadata.txt"
  new_obj: "new_testobj"
  new_key: "new_key"
  new_value: "new_value"
test_8557:
  bucket_name: "obj-metadata8557"
  obj_name: "testobj8557"
  byte_count: 1000
test_8558:
  bucket_name: "obj-metadata8558"
  obj_name: "testobj8558"
  start_range: 2025
  stop_range: 2026
  error_message: "BadRequest"
test_8913:
  bucket_name: "obj-metadata8913"
  obj_name: "testobj8913_"
  obj_count: 500
test_8918:
  bucket_name: "obj-metadata8918"
  obj_name: "testobj8918"
  mb_count: 500