test_1745:
    requests:
        - 100
        - 500
        - 1200
        - 1500

test_1746:
    num_clients:
        - 10
        - 10
        - 12
        - 20
    requests:
        - 10
        - 50
        - 100
        - 500

test_1747:
    num_clients:
        - 1
        - 2
        - 3
        - 4
    requests:
        - 100
        - 100
        - 100
        - 200

test_1748:
    num_clients:
        - 10
        - 2
    requests:
        - 120
        - 150

test_5340:
    nclients:
        - 1000
        - 1200
        - 1500

test_5341:
    nclients:
        - 1000
        - 1500
        - 1000
        - 1500

