error_messages:
  version_not_found_error:
    get_obj_error: "The specified version does not exist"
    head_obj_error: "Not Found"
  invalid_version_id_error:
    get_obj_error: "The specified version does not exist"
    head_obj_error: "Not Found"
  empty_version_id_error:
    get_obj_error: "Version id cannot be the empty string"
    head_obj_error: "Bad Request"
