bucket_workflow:
  bkt_name_prefix: "bktworkflow"
  acc_name_prefix: "bktwrkflowaccnt"
  bkt_permission: "private"
  file_path: "/home/bkt_workflow.txt"
  file_size: 10
test_8535:
  bucket_name_1: "bktworkflow"
  bucket_name_2: "8535-bktworkflow"
test_8536:
  bucket_name: "bktworkflow-8536.bkt"
test_8537:
  bucket_name_1: "bkt"
  bucket_name_2: "bktworkflow-seagateeosbucket-8537-bktworkflow-seagateeosbuckets"
test_8538:
  bucket_list:
    - "a2"
    - "bktworkflow-seagateeosbucket-8537-bktworkflow-seagateeosbucketsbktworkflow-seagateeosbucket"
  error_message: "InvalidBucketName"
test_8539:
  bucket_name: "BKTWORKFLOW"
  error_message: "InvalidBucketName"
test_8540:
  bucket_name: "bktworkflow_8540"
  error_message: "InvalidBucketName"
test_8541:
  bucket_name: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
  start_range: 4
  end_range: 10
  special_chars_list:
    - "!"
    - "*"
    - "("
    - ")"
    - "%"
    - "$"
  special_char_len: 2
  error_message: "Parameter validation failed"
test_8542:
  bucket_name: "192.168.10.20"
  error_message: "InvalidBucketName"
test_8638:
  bucket_name: "bktworkflow-8638"
  bucket_count: 1
test_8639:
  bucket_str: "bktworkflow-8639"
  range: 10
test_8642:
  bucket_name: "bktworkflow-8642"
  error_message: "BucketAlreadyOwnedByYou"
test_8643:
  bucket_name: "bktworkflow-8643"
  bucket_count: 100
test_8644:
  bucket_name: "bktworkflow-8644"
  object_count: 5
  object_str: "object"
  error_message: "BucketNotEmpty"
test_8645:
  bucket_name: "bktworkflow-8645"
  range: 5
  object_str: "object"
test_8646:
  bucket_name: "bktworkflow-8646"
test_8647:
  bucket_name: "bktworkflow-8647"
  bucket_count: 10
test_8648:
  bucket_name: "bktworkflow-8648"
  error_message: "NoSuchBucket"
test_8649:
  bucket_name: "bktworkflow-8649"
  object_count: 5
test_8650:
  bucket_name: "bktworkflow-8650"
  object_count: 5
test_8654:
  bucket_name: "bktworkflow-8654"
  error_message: "Not Found"
test_8655:
  bucket_name: "bktworkflow-8655"
test_8656:
  bucket_name: "bktworkflow-8656"
  bucket_count: 10
test_8658:
  bucket_name: "bktworkflow-8658"
  bucket_location: "us-west-2"

test_432:
  bucket_name: "bktworkflow-432-{}"
  obj_pre: "testobj"
  obj_lst:
    - "obj1"
    - "obj2"
  range: 10

test_433:
  bucket_name: "bktworkflow-433-{}"
  obj_pre: "testobj"
  obj_lst:
    - "obj1"
    - "obj2"
  err_message: "NoSuchBucket"

test_434:
  bucket_name: "bktworkflow-434-{}"
  account_name: "bktwrkflowaccnt434_{}"
  email_id: "acltestaccnt434_{}@seagate.com"
  obj_pre: "testobj"
  range: 10
  err_message: "AccessDenied"

test_435:
  bucket_name: "bktworkflow-435-{}"
  account_name: "bktwrkflowaccnt435_{}"
  email_id: "acltestaccnt435_{}@seagate.com"
  id_str: "id={}"
  obj_pre: "testobj"
  range: 10
