all_users:
  group_uri: "uri=http://acs.amazonaws.com/groups/global/AllUsers"
  del_bkt_force: True
  file_path: "/home/all_users.txt"
  mb_count: 5
  bkt_name_prefix: "allusersbktacl-bkt"
test_375:
  bucket_name: "allusersbktacl-bkt375"
  obj_name: "testobj375"
  permission: "READ"
test_376:
  bucket_name: "allusersbktacl-bkt376"
  obj_name: "testobj376"
  permission: "READ"
  new_obj_name: "testobj"
  err_message: "AccessDenied"
test_377:
  bucket_name: "allusersbktacl-bkt377"
  obj_name: "testobj377"
  permission: "READ"
  err_message: "AccessDenied"
test_378:
  bucket_name: "allusersbktacl-bkt378"
  obj_name: "testobj378"
  permission: "READ"
  err_message: "AccessDenied"
test_379:
  bucket_name: "allusersbktacl-bkt379"
  obj_name: "testobj379"
  permission: "READ"
  err_message: "AccessDenied"
test_380:
  bucket_name: "allusersbktacl-bkt380"
  obj_name: "testobj380"
  permission: "READ"
  acl: "private"
  err_message: "AccessDenied"
test_381:
  bucket_name: "allusersbktacl-bkt381"
  obj_name: "testobj381"
  permission: "READ"
  acl: "private"
  err_message: "AccessDenied"
test_382:
  bucket_name: "allusersbktacl-bkt382"
  obj_name: "testobj382"
  permission: "WRITE"
  err_message: "AccessDenied"
test_383:
  bucket_name: "allusersbktacl-bkt383"
  obj_name: "testobj383"
  new_obj_name: "newtestobj383"
  permission: "WRITE"
  acl: "private"
test_384:
  bucket_name: "allusersbktacl-bkt384"
  obj_name: "testobj384"
  permission: "WRITE"
test_385:
  bucket_name: "allusersbktacl-bkt385"
  obj_name: "testobj385"
  permission: "WRITE"
  err_message: "AccessDenied"
test_386:
  bucket_name: "allusersbktacl-bkt386"
  obj_name: "testobj386"
  permission: "WRITE"
  err_message: "AccessDenied"
test_387:
  bucket_name: "allusersbktacl-bkt387"
  obj_name: "testobj387"
  permission: "WRITE"
  acl: "private"
  err_message: "AccessDenied"
test_388:
  bucket_name: "allusersbktacl-bkt388"
  obj_name: "testobj388"
  permission: "WRITE"
  acl: "private"
  err_message: "AccessDenied"
test_389:
  bucket_name: "allusersbktacl-bkt389"
  obj_name: "testobj389"
  permission: "READ_ACP"
  err_message: "AccessDenied"
test_390:
  bucket_name: "allusersbktacl-bkt390"
  obj_name: "testobj390"
  new_obj_name: "tempobj390"
  permission: "READ_ACP"
  err_message: "AccessDenied"
test_391:
  bucket_name: "allusersbktacl-bkt391"
  obj_name: "testobj391"
  permission: "READ_ACP"
  err_message: "AccessDenied"
test_392:
  bucket_name: "allusersbktacl-bkt392"
  obj_name: "testobj392"
  permission: "READ_ACP"
  err_message: "AccessDenied"
test_393:
  bucket_name: "allusersbktacl-bkt393"
  obj_name: "testobj393"
  permission: "READ_ACP"
test_394:
  bucket_name: "allusersbktacl-bkt394"
  obj_name: "testobj394"
  permission: "READ_ACP"
  acl: "private"
  err_message: "AccessDenied"
test_395:
  bucket_name: "allusersbktacl-bkt395"
  obj_name: "testobj395"
  permission: "READ_ACP"
  acl: "private"
  err_message: "AccessDenied"
test_396:
  bucket_name: "allusersbktacl-bkt396"
  obj_name: "testobj396"
  permission: "WRITE_ACP"
  err_message: "AccessDenied"
test_397:
  bucket_name: "allusersbktacl-bkt397"
  obj_name: "testobj397"
  new_obj_name: "tempobj397"
  permission: "WRITE_ACP"
  err_message: "AccessDenied"
test_398:
  bucket_name: "allusersbktacl-bkt398"
  obj_name: "testobj398"
  permission: "WRITE_ACP"
  err_message: "AccessDenied"
test_399:
  bucket_name: "allusersbktacl-bkt399"
  obj_name: "testobj399"
  permission: "WRITE_ACP"
  err_message: "AccessDenied"
test_400:
  bucket_name: "allusersbktacl-bkt400"
  obj_name: "testobj400"
  permission: "WRITE_ACP"
  err_message: "AccessDenied"
test_401:
  bucket_name: "allusersbktacl-bkt401"
  obj_name: "testobj401"
  permission: "WRITE_ACP"
  new_permission: "FULL_CONTROL"
test_402:
  bucket_name: "allusersbktacl-bkt402"
  obj_name: "testobj402"
  permission: "WRITE_ACP"
  acl: "private"
  err_message: "AccessDenied"
test_403:
  bucket_name: "allusersbktacl-bkt403"
  obj_name: "testobj403"
  permission: "FULL_CONTROL"
test_404:
  bucket_name: "allusersbktacl-bkt404"
  obj_name: "testobj404"
  new_obj_name: "tempobj404"
  permission: "FULL_CONTROL"
test_405:
  bucket_name: "allusersbktacl-bkt405"
  obj_name: "testobj405"
  permission: "FULL_CONTROL"
test_406:
  bucket_name: "allusersbktacl-bkt406"
  obj_name: "testobj406"
  permission: "FULL_CONTROL"
  err_message: "AccessDenied"
test_407:
  bucket_name: "allusersbktacl-bkt407"
  obj_name: "testobj407"
  permission: "FULL_CONTROL"
test_408:
  bucket_name: "allusersbktacl-bkt408"
  obj_name: "testobj408"
  permission: "FULL_CONTROL"
  acl: "private"
test_409:
  bucket_name: "allusersbktacl-bkt409"
  obj_name: "testobj409"
  permission: "FULL_CONTROL"
  acl: "private"
  err_message: "AccessDenied"