object_tagging:
    bkt_name_prefix: "objtag"
    file_path: "/home/obj_tag.txt"
    mb_count: 5
test_9413:
    bucket_name: "objtag9413"
    object_name: "testobj"
    key: "testkey"
    value: "valuekey"
test_9414:
    bucket_name: "objtag9414"
    object_name: "testobj"
    key: "testkey"
    value: "valuekey"
test_9415:
    bucket_name: "objtag9415"
    object_name: "testobj"
    key: "testkey"
    value: "valuekey"
    tag_length: 0
test_9416:
    bucket_name: "objtag9416"
    object_name: "testobj"
    object_tag: "testkey=testvalue"
test_9417:
    bucket_name: "objtag9417"
    object_name: "testobj"
    object_tag: "testkey=testvalue"
test_9418:
    bucket_name: "objtag9418"
    object_name: "testobj"
    object_tag: "testkey=testvalue"
    single_part_size: 40
    total_parts: 5
test_9419:
    bucket_name: "objtag9419"
    object_name: "testobj"
    key: "testkey"
    value: "valuekey"
    tag_count: 10
test_9420:
    bucket_name: "objtag9420"
    object_name: "testobj"
    key: "testkey"
    value: "valuekey"
    tag_count: 20
    error_message: "InvalidTagError"
test_9421:
    bucket_name: "objtag9421"
    object_name: "testobj"
    key: "testkey"
    value: "valuekey"
    error_message: "MalformedXML"
test_9422:
    bucket_name: "objtag9422"
    object_name: "testobj"
    key: "testkey"
    value: "valuekey"
    duplicate_key: False
test_9423:
    bucket_name: "objtag9423"
    object_name: "testobj"
    key: "organizationCreateatagwhosekeyisupto128UnicodecharactersinlengtCreateatagwhosekeyisupto128Unicodecharacterslengthshouldbe128cha"
    value: "valuekey"
test_9424:
    bucket_name: "objtag9424"
    object_name: "testobj"
    key: "seagateorganizationCreateatagwhosekeyisupto128UnicodecharactersinlengtCreateatagwhosekeyisupto128Unicodecharacterslengthshouldbe128cha"
    value: "valuekey"
    error_message: "InvalidTagError"
test_9425:
    bucket_name: "objtag9425"
    object_name: "testobj"
    key: "testkey"
    value: "organizationCreateatagwhosekeyisupto128UnicodecharactersinlengtCreateatagwhosekeyisupto128Unicodecharacterslengthshouldbe128charorganizationCreateatagwhosekeyisupto128UnicodecharactersinlengtCreateatagwhosekeyisupto128Unicodecharacterslengthshouldbe128cha"
test_9426:
    bucket_name: "objtag9426"
    object_name: "testobj"
    key: "testkey"
    value: "caationCreateatagwhosekeyisupto128UnicodecharactersinlengtCreateatagwhosekeyisupto128Unicodecharacterslengthshouldbe128charorganaationCreateatagwhosekeyisupto128UnicodecharactersinlengtCreateatagwhosekeyisupto128Unicodecharacterslengthshouldbe128charorganaationCreateatagwhosekeyisupto128UnicodecharactersinlengtCreateatagwhosekeyisupto128Unicodecharacterslengthshouldbe128charorgaaationCreateatagwhosekeyisupto128UnicodecharactersinlengtCreateatagwhosekeyisupto128Unicodecharacterslengthshouldbe128charorgaaaaaaaa"
    error_message: "InvalidTagError"
test_9427:
    bucket_name: "objtag9427"
    object_name: "testobj"
    key1: "testkey"
    key2: "TestKey"
    value: "testvalue"
test_9428:
    bucket_name: "objtag9428"
    object_name: "testobj"
    key: "testkey"
    value1: "TestValue"
    value2: "testvalue"
test_9429:
    bucket_name: "objtag9429"
    object_name: "testobj"
    key: "project+-=._:/a"
    value: "EOSproject+-=._:/2"
test_9430:
    bucket_name: "objtag9430"
    object_name: "testobj"
    key: "testkey"
    value: "testvalue"
    invalid_chars_list:
        - "!"
        - "{"
        - "}"
        - "`"
        - "^"
        - "%"
        - "<"
        - ">"
        - "["
        - "]"
        - "#"
        - "|"
        - "~"
        - "?"
        - "*"
    error_message: "InvalidTagError"
test_9431:
    bucket_name: "objtag9431"
    object_name: "testobj"
    key: "testkey"
    value: "testvalue"
    invalid_chars_list:
        - "!"
        - "{"
        - "}"
        - "`"
        - "^"
        - "%"
        - "<"
        - ">"
        - "["
        - "]"
        - "#"
        - "|"
        - "~"
        - "?"
        - "*"
    error_message: "InvalidTagError"
test_9432:
    bucket_name: "objtag9432"
    object_name: "testobj"
    key: "testkey"
    value: "testvalue"
test_9433:
    bucket_name: "objtag9433"
    object_name: "testobj"
    object_tag: "testkey=testvalue"
test_9434:
    bucket_name: "objtag9434"
    object_name: "testobj"
    key: "testkey"
    value: "testvalue"
    object_count: 2
    tag_count: 10
test_9435:
    bucket_name: "objtag9435"
    object_name: "testobj"
    key: "testkey"
    value: "testvalue"
    object_tag: "project3=EOS-v1-1"
test_9436:
    bucket_name: "objtag9436"
    object_name: "testobj"
    key1: "testkey1"
    value1: "testvalue1"
    key2: "testkey2"
    value2: "testvalue2"
    object_tag: "project=EOS"
    tag_len: 0
test_9437:
    bucket_name: "objtag9437"
    object_name: "testobj"
    object_tag: "pproject1=EOS-v1&project2=EOS-v2&project3=EOS-v3&project4=EOS-v4&project5=EOS-v5&project6=EOS-v6&project7=EOS-v7&project8=EOS-v8&project9=EOS-v9&project10=EOS-v10"
    key: "testkey"
    value: "dsfsdfsdfsfsfsdfdfgdggdfsfsrggfffgfgdfxvfsfsjfjhhfjsdffsjdfhhgjhjjhbjhbjbjbjbjbjbjbjbjbjhjhjshjshsahdiuedscbdbcscb"
    tag_count: 10
test_9438:
    bucket_name: "objtag9438"
    object_name: "testobj"
    key: "testkey"
    value: "testvalue"
    tag_count: 15
    error_message: "InvalidTagError"
test_9439:
    bucket_name: "objtag9439"
    object_name: "testobj"
    key: "testkey"
    value: "testvalue"
    error_message: "NoSuchKey"
test_9440:
    bucket_name: "objtag9440"
    object_name: "testobj"
    error_message: "NoSuchKey"
test_9441:
    bucket_name: "objtag9441"
    object_name: "testobj"
    error_message: "NoSuchKey"
test_9442:
    bucket_name: "objtag9442"
    object_name: "testobj"
    key: "testkey"
    value: "testvalue"
    error_message: "NoSuchKey"
test_9443:
    bucket_name: "objtag9443"
    object_name: "testobj"
    error_message: "NoSuchKey"