#NOTE: Password manager changes for encryption and decryption are done for this file
iam_user_login:
  user_name_prefix: "iamuser"
  acc_name_prefix: "iamaccount"
test_9824:
  user_name: "iamuser9824"
  password: "pHn3CxMXukvTVsrRtuXLZJYZ456P7GPqbJ9pXuqnnwA="
  password_reset: True
  new_password: "xjaSUo4RN1hzWjtRxbQD1QEG5kRKc+68E+Dj7PR16Nk="
test_9825:
  user_name: "iamuser9825"
  password: "p/oNeZU22mOz0HEvhDBfDzQneAEayCTE+A2fzbzcOIU="
  err_message: "NoSuchEntity"
test_9826:
  user_name: "iamuser9826"
  password: "IF3OQHWNXva4PJRak+mDiXyysjuH0RdZSHde8L2T8js="
  password_reset: True
  new_password: None
  err_message: "PasswordPolicyVoilation"
test_9828:
  user_name: "iamuser9828"
  password: "r228j6/9zt6jRPmzNfEQ+QckfmEQfmFNrUgyyGeNNjs="
  password_reset: True
  new_password: "kIBdqNjdRrmF21KRTJEsuH+1ioZk71NfxB1sxdc264zb5vfdVkH5HFKMu3IDWcfVe1HY3rinkmLCJWeAPgTx2CUjr6x8J8dByHSgaxamGLzUPbEnt0k6k1zvJuM/9R8P+cHUkxqnHh8AZiF5mNgvyjvPQqo2VejNlsIOMpmex9Sj+de41t0uIlrfE3RhU0tB9ttgCOEVRnlDhJzJB1dXdA=="
test_9829:
  user_name: "iamuser9829"
  password: "AI/FSXlSY23YVxh09sMDXONClvgKk89Ch5n0KouV5o4="
  password_reset: True
  new_password: "PomcbXwbbhnSGcLSBMb3LFUloFpEiSeM+V+92dJtU+DYvl8pCcIyNo4fjt4mliK1wKNiNotvTRq2qKtEqPl/8bPVH2IalqVa68+8dHj6xGpx4yo8nw1udQapZs7npiPO70SxOdKJafzl8DBivozVUfC/XZ0xiFy1aWDICOiSQpjOKYMXEUAV52yzYSTK7ugVpTOz0vR7Twn7jssrFtun6g=="
  err_message: "PasswordPolicyVoilation"
test_9830:
  user_name: "iamuser9830"
  password: "ypgWOkqNNsVscOWu82nVRHTFZESIMk1DKT3lQLVWFLk="
  password_reset: False
  new_password: "+GEMUYEz6+bFdclu/kd79rg8qh2//9Z0V1DnqCHiXzg="
  new_password_reset: True
test_9831:
  user_name: "iamuser9831"
  password: "a9QLKFuCAcyQDKJvA4H3SbHhybUk/7DU2uXvzr6p9sk="
  err_message: "NoSuchEntity"
test_9832:
  user_name: "iamuser9832"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  password_reset: False
  special_char_pwd:
    - "9i0YFGVrSRCkWbFRdtcEqEqH93UfdEbZ1hG2ddaKDnU="
    - "AIGL/7QSRnIblF+CxTNxaXcD5lm6YvpmuwWEn9i7+aw="
    - "hOkcMENfHOqUUgNxmF8XvybRA3g86uHkNqm9YGD1g7I="
    - "O9l0stg5O7l2e4fLUadEoGrK5ZxAm18CDkv5b+te0fE="
    - "MFQ8yor+DGx+4ofiVjY4uTVIOLSfrQqujElzeXYOqHw="
    - "Sgb35cICs1Di02XxTxcWnv/e7HxUVQDlVLVecCAntG0="
test_9833:
  user_name: "iamuser9833"
  password: "8pPkYatDx8p747rMmEetKY8bNy9/FP1yskp2uWu7Enw="
  password_reset: True
  new_password: "3yJbrKV8wBX6jH1OauovEb2WpAr9G2dNUKm41i9rum0="
test_9834:
  user_name: "iamuser9834"
  password: "3JM1hp8xFmN1D2mQJtOYCSKp/uJtpIwu7hJzMEI0UTc="
  new_password: "DLzaqFOr0UOgOKrWI3P3XqNuTvF2i1Kq+kSgKF3w5AQ="
test_9835:
  user_name: "iamuser9835"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  password_reset: True
  err_message: "Please provide password or password-reset flag"
test_9836:
  user_name: "iamuser9836"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  password_reset: True
test_9837:
  user_name: "iamuser9837"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  password_reset: True
  err_message: "NoSuchEntity"
test_9838:
  user_name: "iamuser9838"
  password: None
  password_reset: True
  err_message: "PasswordPolicyVoilation"
test_9840:
  user_name: "iamuser9840"
  password: "4XIWHPsV9dmVs8u1CLGftbQ7fhIK2zh0sZpjAf+hNF2mzpN6cKZ53asTf0IG3HUina6WrTV/+CEnEQs6wpws+LIXc6ZSpZdNx69pX+BLswdqnznirnoePDqyEgYPR8nxhCL74kyM+oAOGi/pgbGThfllnAiVjOUBbNNmWXJ+wJplhZQATanJ6R0W8MZxlYBeXuGxEYL3J6dSaycoRfOinQ=="
  password_reset: True
test_9841:
  user_name: "iamuser9841"
  password: "CwCrXx838o3H58net0yeCg/jJgOS4OLsEhAUu6LlVpB9/Sq0wwsg82cSnXQk8MfmhKjhnYRR2dQz893JNZG66G0/3xPWk7s72miXYDxIoQEM7zQ1D0w+t/+4xAjpw8viwUo9Ls5gRax+4IGNsIEwhD6Te073tr6an/s4iuhnfsDh3xHSvBSr8qkc8na8e0VDhZmcsS9T8rA/uydXMQ470Q=="
  password_reset: True
  err_message: "PasswordPolicyVoilation"
test_9842:
  user_name: "iamuser9842"
  password: "vhiTxsPCQUtEyW2imNVg8iYrgbA73G/RONETSw7i3tM="
  password_reset: True
test_9843:
  user_name: "iamuser9843"
  special_char_pwd:
    - "xZ4MvdpVZchbVOZASxVv9k4iqC6vVs5eE7eUf4FIXZw="
    - "LvnCPJgnbHybOy++aQqnAYm+xMEYK0Rv5WihCTRdbDc="
    - "SWCB7uQ3sCsHdSWYHvRzvWbQaRtCSe3PkvKd2dOVqQ0="
    - "OjSOg11x7jqYFCV4oIaPWG2Xp+qRWGHV+d0KjGZpoIE="
    - "xQCBE/BWer4HeYWU+m1IShXRkHIjEv9PBq3z3v3f2i4="
    - "CxD7a9fqP4y+f9c7kC4ahb1EzfsBHIwpl7bKfj8HCeY="
  password_reset: True
test_9844:
  user_name: "iamuser9844"
  user_name_suffix: "_{}"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  password_reset: True
  no_of_users: 101
test_9845:
  user_name: "iamuser9845"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  password_reset: False
test_9846:
  user_name: "iamuser9846"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  password_reset: True
test_9847:
  user_name: "iamuser9847"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
test_9848:
  user_name: "iamuser9848"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  both_reset_options: True
test_9849:
  user_name: "iamuser9849"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  password_reset: True
test_9850:
  user_name: "iamuser9850"
  err_message: "NoSuchEntity"
test_9851:
  user_name: "iamuser9851"
  err_message: "NoSuchEntity"
test_9876:
  user_name: "iamuser9876"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  new_password: "DLzaqFOr0UOgOKrWI3P3XqNuTvF2i1Kq+kSgKF3w5AQ="
test_9877:
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  user_access_key: "dummy_access_key"
  user_secret_key: "dummy_secret_key"
  new_password: "DLzaqFOr0UOgOKrWI3P3XqNuTvF2i1Kq+kSgKF3w5AQ="
  err_message: "InvalidAccessKeyId"
test_9878:
  user_name: "iamuser9878"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  new_password: "DLzaqFOr0UOgOKrWI3P3XqNuTvF2i1Kq+kSgKF3w5AQ="
test_9879:
  user_name: "iamuser9879"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  new_password: "a"
  err_message: "PasswordPolicyVoilation"
test_9880:
  user_name: "iamuser9880"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  new_password: "4XIWHPsV9dmVs8u1CLGftbQ7fhIK2zh0sZpjAf+hNF2mzpN6cKZ53asTf0IG3HUina6WrTV/+CEnEQs6wpws+LIXc6ZSpZdNx69pX+BLswdqnznirnoePDqyEgYPR8nxhCL74kyM+oAOGi/pgbGThfllnAiVjOUBbNNmWXJ+wJplhZQATanJ6R0W8MZxlYBeXuGxEYL3J6dSaycoRfOinQ=="
test_9881:
  user_name: "iamuser9881"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  new_password: "CwCrXx838o3H58net0yeCg/jJgOS4OLsEhAUu6LlVpB9/Sq0wwsg82cSnXQk8MfmhKjhnYRR2dQz893JNZG66G0/3xPWk7s72miXYDxIoQEM7zQ1D0w+t/+4xAjpw8viwUo9Ls5gRax+4IGNsIEwhD6Te073tr6an/s4iuhnfsDh3xHSvBSr8qkc8na8e0VDhZmcsS9T8rA/uydXMQ470Q=="
  err_message: "InvalidParameterValue"
test_9882:
  user_name: "iamuser9882"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  password_reset: True
  list_special_char_pwd:
    - "xZ4MvdpVZchbVOZASxVv9k4iqC6vVs5eE7eUf4FIXZw="
    - 'mCrRjCVmw8QDvfgohmP/S8Xfovbdq8S2JXdKXgcHs+g='
    - '++cmX3GLURLzQ+TVCG6FittvTMXbWMrj+H1hIqZIBPc='
    - "xQCBE/BWer4HeYWU+m1IShXRkHIjEv9PBq3z3v3f2i4="
    - "F3n+Q8yWcvdYMpZSdgaWuQhY3tsDPx+tM/RFZJXdFmk="
    - 'su5ibVDRAwBFfnNkr5guXAWdcfLOnuNPC4fAUbmjH10='
    - "GGVIMnuo60BI5fBgalcLe6MFCPxqIKQgHSx1R1G8eTY="
    - "P4dpkPtLAcswLMN+f1OnLUgECQX6QPOiiYtJXBzE1Fs="
    - 'biRcbHB3Xa8JsBzvaU9Rnd+Qgzd5e8kDw0J/i+tREZY='
    - "0Wzknj2AVsNR6ZgtWGpW/GPNjTVSLqlGkaayZmLuD3w="
    - "s2DAJ53F3TcdA2qZXxPB0ThvBcS7/ZhXrvEhDaxb+k4="
    - "zs7bwHv/tXAeIud2ULjeJuOqHEEwUAv5DJEWDWICObo="
test_9883:
  user_name: "iamuser9883"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  password_reset: True
  err_message: "InvalidPassword"
test_9884:
  user_name: "iamuser9884"
  password: "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  new_password: "U7UQ7NoFYowF5pqxRl5UzHFkrySVkfWI7pQL4nd+uQ0="
  dummy_access_key: "aldkjakjfakjfklafj"
  dummy_secret_key: "kahdahfouk692583"
  err_message: "InvalidAccessKeyId"
test_9923:
  account_name: "iamaccount9923"
  email_id: "@seagate.com"
  user_name: "iamuser9923"
  account_password: "DRU9Oz1HtTY5hkRuJrc0WtCpClN8v+ZfcgAckKTqnq0="
  user_password:  "MKfKFPvnz+bywHQ4bPCB0ty8+jz1+YSHPHfUOCM/bQU="
  password_reset: False
test_9924:
  account_name: "iamaccount9924"
  email_id: "@seagate.com"
  user_name: "dummy_user"
  user_password: "AZayKOusURwffmkBDmZS9oQ6Q3V1XAIJ+BL6dYp49WI="
  err_message: "NoSuchEntity"
test_9925:
  account_name: "iamaccount9925"
  email_id: "@seagate.com"
  user_name: "iamuser9925"
  user_password: "AZayKOusURwffmkBDmZS9oQ6Q3V1XAIJ+BL6dYp49WI="
  err_message: "NoSuchEntity"
test_9927:
  account_name: "iamaccount99271"
  email_id: "@seagate.com"
  user_name: "iamuser9927"
  user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="
  bucket_name: "iambkt9927"
test_9928:
  account_name: "iamaccount9928"
  email_id: "@seagate.com"
  user_name: "iamuser9928"
  user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="
  dummy_access_key: "qeopioErUdjalkjfaowf"
  dummy_secret_key: "AslkfjfjksjRsfjlskgUljflglsd"
  dummy_session_token: "2wslfaflk1aldjlakjfkljf67skhvskjdjiwfha"
  err_message: "InvalidAccessKeyId"
  bucket_name: "iambkt9928"
test_9929:
  account_name: "iamaccount9929"
  email_id: "@seagate.com"
  user_name: "iamuser9929"
  user_password: "AZayKOusURwffmkBDmZS9oQ6Q3V1XAIJ+BL6dYp49WI="
  err_message: "InvalidCredentials"
test_9930:
  account_name: "iamaccount9930"
  email_id: "@seagate.com"
  user_name: "iamuser9930"
  user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="
  password_reset: False
test_9931:
  account_name: "iamaccount9931"
  email_id: "@seagate.com"
  user_name: "iamuser9931"
  user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="
  duration: 1200
  bucket_name: "iambkt9931"
  err_message: "ExpiredToken"
test_9932:
  account_name: "iamaccount99320"
  email_id: "@seagate.com"
  user_name: "iamuser9932"
  user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="
  duration: 800
  err_message: "MinDurationIntervalNotMaintained"
test_9936:
  account_name: "iamaccount9936"
  email_id: "@seagate.com"
  user_name: "iamuser9936"
  user_password: "BPXmk6sHpfPrBU/wRJuKJ9FcdHXVqgnSHJVDwG/GOFs="
  password_reset: False
  err_message: "InvalidClientTokenId"
