# CORTX LC specific Delayed Delete test config
test_28993:
  file_size: 3000
  total_parts: 3

# CORTX RGW specific Async Delete test config
# Fixed object sizes to test in MB
fixed_obj_size:
  - 1
  - 10
  - 1024
  - 5120

# Random object size range in MB
random_obj_size:
  min: 1
  max: 5120

gc_min_wait_time: 900
space_reclaim_retry_time: 300
space_reclaim_max_retries: 5
