data_path:
  bkt_name_prefix: "dpv"
  acc_name_prefix: "dpv-acc"
  bkt_permission: "private"
  email_suffix: "@seagate.com"
  file_path: "/home/bkt-dp.txt"
  cmd_msg: "core."
  s3bench_path: "/root/go/bin"
  endpoint: "https://s3.seagate.com"
  s3bench_cmd: "go run s3bench -accessKey={} -accessSecret={} -bucket={} -endpoint={} -numClients={} -numSamples={} -objectNamePrefix={}"
  obj_size: 8388608
  clients: 100
  samples: 100


test_1696:
  bucket_name: "dpv-bkt1696"
  object_name: "dpv-obj1696"
  obj_size: 1

test_1697:
  bucket_name: "dpv-bkt1697"
  object_name: "dpv-obj1697"
  obj_size: 1000

test_1698:
  bucket_name: "dpv-bkt1698"
  object_name: "dpv-obj1698"
  obj_size: 1
  size_mb: "1M"

test_1699:
  bucket_name: "dpv-bkt1699"
  object_name: "dpv-obj1699"
  obj_size: 10
  size_mb: "1M"

test_1700:
  bucket_name: "dpv-bkt1700"
  object_name: "dpv-obj1700"
  obj_size: 100
  size_mb: "1M"

test_1701:
  bucket_name: "dpv-bkt1701"
  object_name: "dpv-obj1701"
  obj_size: 1000
  size_mb: "1M"

test_1702:
  bucket_name: "dpv-bkt1702"
  object_name: "dpv-obj1702"
  obj_size: 10000
  size_mb: "1M"

test_1703:
  bucket_name: "dpv-bkt1703"
  object_name: "dpv-obj1703"
  obj_prefix: "dpv-obj1703"
  obj_size: 1

test_1704:
  bucket_name: "dpv-bkt1704"
  object_name: "dpv-obj1704"
  obj_prefix: "dpv-obj1704"
  obj_size: 1000

test_1705:
  bucket_name: "dpv-bkt1705"
  object_name: "dpv-obj1705"
  obj_prefix: "dpv-obj1705"
  obj_size: 1
  size_mb: "1M"

test_1706:
  bucket_name: "dpv-bkt1706"
  object_name: "dpv-obj1706"
  obj_prefix: "dpv-obj1706"
  obj_size: 10
  size_mb: "1M"

test_1707:
  bucket_name: "dpv-bkt1707"
  object_name: "dpv-obj1707"
  obj_prefix: "dpv-obj1707"
  obj_size: 100
  size_mb: "1M"

test_1708:
  bucket_name: "dpv-bkt1708"
  object_name: "dpv-obj1708"
  obj_prefix: "dpv-obj1708"
  obj_size: 1000
  size_mb: "1M"

test_1709:
  bucket_name: "dpv-bkt1709"
  object_name: "dpv-obj1709"
  obj_prefix: "dpv-obj1709"
  obj_size: 10000
  size_mb: "1M"

test_1745:
  bucket_name: "dpv-bkt1745"
  obj_name: "dpv-obj1745"
  num_clients: 1
  requests:
    - 100
    - 500
    - 1200
    - 1500
  obj_name_pref: "dpv_obj_"
  s3bench_obj_size: 8388608
  skip_cleanup: True
  verbose: True

test_1746:
  bucket_name: "dpv-bkt1746"
  obj_name: "dpv-obj1746"
  num_clients:
    - 10
    - 10
    - 12
    - 20
  requests:
    - 10
    - 50
    - 100
    - 500
  obj_name_pref: "dpv_obj_"
  s3bench_obj_size: 8388608
  skip_cleanup: True
  verbose: True

test_1747:
  bucket_name: "dpv-bkt1747"
  obj_name: "dpv-obj1747"
  bkt_count: 5
  num_clients:
    - 1
    - 2
    - 3
    - 4
  requests:
    - 100
    - 100
    - 100
    - 200
  obj_name_pref: "dpv_obj_"
  s3bench_obj_size: 8388608
  skip_cleanup: True
  verbose: True

test_1748:
  bucket_name: "dpv-bkt1748"
  obj_name: "dpv-obj1748"
  bkt_count: 2
  num_clients:
    - 10
    - 2
  requests:
    - 120
    - 150
  obj_name_pref: "dpv_obj_"
  s3bench_obj_size: 8388608
  skip_cleanup: True
  verbose: True
