common_vars:
  date_format: "%Y-%m-%d"
  openldap_path: "/etc/openldap"
  ldap_data_path: "/var/lib"
  ls_cmd: "ls /etc/openldap/"
  ch_owner_cmd: "chown -R ldap:ldap {}"
  chk_owner_cmd: "ls -l {}"
  slapd_dir: "slapd.d"
  ldap_data_dir: "ldap"
  ldap_owner: "ldap"
  slapd_service: "slapd"
  slapd_err: "slapd.d directory is not present under {}"
  backup_path: "/root/backup"
  ls_backup_path: "ls /root/backup"
  backup_dir_err: "Backup directory {} is not created under {}"
  cr_dir_err: "{} directory is not created under {}"
  restore_dir_err: "Directory is not restored under {}"
  ch_owner_err: "Failed to change owner of {}"
  slapcat_cmd: "slapcat -n {} -l {}/{}"
  cfg_backup_file: "config.ldif"
  data_backup_file: "data.ldif"
  rm_dir_cmd: "rm -rf {}"
  mk_dir_cmd: "mkdir {}"
  press_enter: "\n"
  pwd_prompt_msg: "Enter RootDnPasword: "
  root_pwd: "oOPdW3a5sMcVfchrdiJGDSIrIu49ByTsprb/jIQbowU="
  decode_format: "utf-8"
  output_bytes: 9999
  root_prmpt: "~]# "
  scr_dir_prmpt: " scripts]# "
  channel_time_pause: 4
  restart_serv_pause: 30
  ch_pwd_cmd: "sh enc_ldap_passwd_in_cfg.sh -p {} -c {}"
  output_str: "You need to Restart Slapd"
  temp_path: "authserver.properties"
  backup_ldap_dir_cmd: "mv /var/lib/ldap /root/backup/{}"
  restore_ldap_cmd: "slapadd -n 2 -F /etc/openldap/slapd.d -l {}/data.ldif"
  backup_slapd_dir_cmd: "mv /etc/openldap/slapd.d /root/backup/{}"
  restore_slapd_cmd: "slapadd -n 0 -F /etc/openldap/slapd.d -l {}/config.ldif"
  ls_ldap_data_cmd: "ls /var/lib/"
  ls_slapd_dir: "ls /etc/openldap/slapd.d"
  ldap_data_err: "Ldap data directory is not present under {}"
  cr_slapd_dir_cmd: "mkdir /etc/openldap/slapd.d"
  cr_ldap_dir_cmd: "mkdir /var/lib/ldap"
  ldap_config_files:
    - "cn=config"
    - "cn=config.ldif"
  output_msg: "OpenLdap password Updated Successfully"
  login_pwd_section: "ldapLoginPW"
  err_message: "Failed to change openldap password"

test_5066:
  db_no: 0

test_5067:
  db_no: 2
  ldap_data_dir_err: "Ldap data directory was not present under {}"

test_5068:
  db_no: 0

test_5069:
  db_no: 0

test_5070:
  db_no: 2

test_5071:
  db_no: 2

test_5073:
  new_pwd: "bIH1A5ciaw74MiXpQQ4MMWF5mBNfSg4ksEexscTJl7A/zjNUNoAmXo0otXZfv6At"

test_5074:
  new_pwd: "pQcWJA3X+q+rEazSHfUi2KC+2wD9pFjf6BYFXRV2fCRW0AT3wsN+1Ja961SW0aAY"

test_5075:
  new_pwd: "vfbzvj21TW6Om4Q8FN4cTs61MtxrazWieo05GD4wFJ6iUwlbQA2Y2gEDtBZSJ3mMtLIFdltdVHlZIYXFwA8+IA=="

test_5076:
  new_pwd: "4FKjc7D0fN5oVDhoubV0lyGl4qB3i8uOL7XHKwjgDWU="
  err_message: "Ldap password not specified"
