test_1:
  TEST_ID:
  start_range: 1Kb
  end_range: 100Kb
  result_duration: 1h
  sessions_per_node: 1
  tool: s3bench

test_2:
  TEST_ID:
  start_range: 100Kb
  end_range: 1Mb
  result_duration: 4h
  sessions_per_node: 2
  tool: s3bench

test_3:
  TEST_ID:
  start_range: 1Mb
  end_range: 10Mb
  result_duration: 1d
  sessions_per_node: 3
  tool: s3bench

test_4:
  TEST_ID:
  start_range: 10Mb
  end_range: 20Mb
  result_duration: 1d
  sessions_per_node: 5
  tool: s3bench

test_5:
  TEST_ID:
  start_range: 20Mb
  end_range: 100Mb
  result_duration: 3d
  sessions_per_node: 8
  tool: s3bench

test_6:
  TEST_ID:
  start_range: 100Mb
  end_range: 500Mb
  result_duration: 5d
  sessions_per_node: 13
  tool: s3bench

test_7:
  TEST_ID:
  start_range: 500Mb
  end_range: 1Gb
  result_duration: 7d
  sessions_per_node: 21
  tool: s3bench

test_8:
  TEST_ID:
  start_range: 1Gb
  end_range: 2Gb
  result_duration: 15d
  sessions_per_node: 34
  tool: s3bench

test_9:
  TEST_ID:
  start_range: 2Gb
  end_range: 5Gb
  result_duration: 20d
  sessions_per_node: 55
  tool: s3bench

test_10:
  TEST_ID:
  start_range: 5Gb
  end_range: 10Gb
  result_duration: 25d
  sessions_per_node: 89
  tool: s3bench

test_11:
  TEST_ID:
  start_range: 10Gb
  end_range: 20Gb
  result_duration: 30d
  sessions_per_node: 144
  tool: s3bench

test_12:
  TEST_ID:
  start_range: 20Gb
  end_range: 50Gb
  result_duration: 40d
  sessions_per_node: 233
  tool: s3bench
