test_1:
  TEST_ID:
  start_range: 0Kb
  end_range: 100Kb
  result_duration: 01h00m00s
  sessions_per_node: 1
  tool: s3bench

test_2:
  TEST_ID:
  start_range: 100Kb
  end_range: 1Mb
  result_duration: 04h00m00s
  sessions_per_node: 2
  tool:

test_3:
  TEST_ID:
  start_range: 1Mb
  end_range: 10Mb
  result_duration: 24h00m00s
  sessions_per_node: 3
  tool:

test_4:
  TEST_ID:
  start_range: 10Mb
  end_range: 20Mb
  result_duration: 24h00m00s
  sessions_per_node: 5
  tool:

test_5:
  TEST_ID:
  start_range: 20Mb
  end_range: 100Mb
  result_duration: 24h00m00s
  sessions_per_node: 8
  tool:

test_6:
  TEST_ID:
  start_range: 100Mb
  end_range: 500Mb
  result_duration: 24h00m00s
  sessions_per_node: 13
  tool:

test_7:
  TEST_ID:
  start_range: 500Mb
  end_range: 1Gb
  result_duration: 24h00m00s
  sessions_per_node: 21
  tool:

test_8:
  TEST_ID:
  start_range: 1Gb
  end_range: 2Gb
  result_duration: 168h00m00s
  sessions_per_node: 34
  tool:

test_9:
  TEST_ID:
  start_range: 2Gb
  end_range: 5Gb
  result_duration: 120h00m00s
  sessions_per_node: 55
  tool:

test_10:
  TEST_ID:
  start_range: 5Gb
  end_range: 10Gb
  result_duration: 120h00m00s
  sessions_per_node: 89
  tool:

test_11:
  TEST_ID:
  start_range: 10Gb
  end_range: 20Gb
  result_duration: 120h00m00s
  sessions_per_node: 144
  tool:

test_12:
  TEST_ID:
  start_range: 20Gb
  end_range: 50Gb
  result_duration: 120h00m00s
  sessions_per_node: 233
  tool:
