test_1:
    TEST_ID: TEST-36211
    object_size:
        start: 1Gb
        end: 4Gb
    part_range:
        start: 50
        end: 100
    result_duration: 2h
    sessions: 5  # One object per session.
    tool: s3api
    operation: multipart

test_2:
    TEST_ID: TEST-36216
    object_size:
        start: 4Gb
        end: 8Gb
    part_range:
        start: 100
        end: 200
    result_duration: 2h
    sessions: 5
    tool: s3api
    operation: multipart

test_3:
    TEST_ID: TEST-36217
    object_size:
        start: 8Gb
        end: 16Gb
    part_range:
        start: 200
        end: 300
    result_duration: 20h
    sessions: 10
    tool: s3api
    operation: multipart

test_4:
    TEST_ID: TEST-36218
    object_size:
        start: 16Gb
        end: 32Gb
    part_range:
        start: 300
        end: 400
    result_duration: 1d
    sessions: 10
    tool: s3api
    operation: multipart

test_5:
    TEST_ID: TEST-36219
    object_size:
        start: 32Gb
        end: 64Gb
    part_range:
        start: 400
        end: 500
    result_duration: 1d
    sessions: 15
    tool: s3api
    operation: multipart

test_6:
    TEST_ID: TEST-36220
    object_size:
        start: 64Gb
        end: 128Gb
    part_range:
        start: 500
        end: 600
    result_duration: 2d
    sessions: 15
    tool: s3api
    operation: multipart

test_7:
    TEST_ID: TEST-36221
    object_size:
        start: 128Gb
        end: 256Gb
    part_range:
        start: 600
        end: 700
    result_duration: 2d
    sessions: 20
    tool: s3api
    operation: multipart

test_8:
    TEST_ID: TEST-36222
    object_size:
        start: 256Gb
        end: 512Gb
    part_range:
        start: 700
        end: 800
    result_duration: 4d
    sessions: 20
    tool: s3api
    operation: multipart

test_9:
    TEST_ID: TEST-36223
    object_size:
        start: 512Gb
        end: 1Tb
    part_range:
        start: 800
        end: 1600
    result_duration: 5d
    sessions: 25
    tool: s3api
    operation: multipart

test_10:
    TEST_ID: TEST-36224
    object_size:
        start: 1Tb
        end: 2Tb
    part_range:
        start: 1600
        end: 3200
    result_duration: 5d
    sessions: 25
    tool: s3api
    operation: multipart

test_11:
    TEST_ID: TEST-36225
    object_size:
        start: 2Tb
        end: 4Tb
    part_range:
        start: 3200
        end: 6400
    result_duration: 5d
    sessions: 30
    tool: s3api
    operation: multipart

test_12:
    TEST_ID: TEST-36226
    object_size:
        start: 4Tb
        end: 5Tb
    part_range:
        start: 6400
        end: 10000
    result_duration: 5d
    sessions: 30
    tool: s3api
    operation: multipart
