test_1:
  TEST_ID: TEST-35678
  object_size:
    start : 0Kib
    end : 100Kib
  result_duration: 1h
  sessions_per_node: 1
  tool: s3api
  operation: object

test_2:
  TEST_ID: TEST-35679
  object_size:
    start: 100Kib
    end: 1Mib
  result_duration: 4h
  sessions_per_node: 2
  tool: s3api
  operation: object

test_3:
  TEST_ID: TEST-35680
  object_size:
    start: 1Mib
    end: 10Mib
  result_duration: 20h
  sessions_per_node: 3
  tool: s3api
  operation: object

test_4:
  TEST_ID: TEST-35681
  object_size:
    start: 10Mib
    end: 20Mib
  result_duration: 1d
  sessions_per_node: 5
  tool: s3api
  operation: object

test_5:
  TEST_ID: TEST-35682
  object_size:
    start: 20Mib
    end: 100Mib
  result_duration: 1d
  sessions_per_node: 8
  tool: s3api
  operation: object

test_6:
  TEST_ID: TEST-35683
  object_size:
    start: 100Mib
    end: 500Mib
  result_duration: 2d
  sessions_per_node: 13
  tool: s3api
  operation: object

test_7:
  TEST_ID: TEST-35684
  object_size:
    start: 500Mib
    end: 1Gib
  result_duration: 2d
  sessions_per_node: 21
  tool: s3api
  operation: object

test_8:
  TEST_ID: TEST-35685
  object_size:
    start: 1Gib
    end: 2Gib
  result_duration: 4d
  sessions_per_node: 34
  tool: s3api
  operation: object

test_9:
  TEST_ID: TEST-35686
  object_size:
    start: 2Gib
    end: 5Gib
  result_duration: 5d
  sessions_per_node: 55
  tool: s3api
  operation: object
