test_1:
  TEST_ID: TEST-35678
  object_size:
    start : 0Kib
    end : 100Kib
  result_duration: 1h
  sessions_per_node: 1
  samples: 100
  tool: s3bench

test_2:
  TEST_ID: TEST-35679
  object_size:
    start: 100Kib
    end: 1Mib
  result_duration: 4h
  sessions_per_node: 2
  samples: 200
  tool: s3bench

test_3:
  TEST_ID: TEST-35680
  object_size:
    start: 1Mib
    end: 10Mib
  result_duration: 20h
  sessions_per_node: 3
  samples: 300
  tool: s3bench

test_4:
  TEST_ID: TEST-35681
  object_size:
    start: 10Mib
    end: 20Mib
  result_duration: 1d
  sessions_per_node: 5
  samples: 400
  tool: s3bench

test_5:
  TEST_ID: TEST-35682
  object_size:
    start: 20Mib
    end: 100Mib
  result_duration: 1d
  sessions_per_node: 8
  samples: 500
  tool: s3bench

test_6:
  TEST_ID: TEST-35683
  object_size:
    start: 100Mib
    end: 500Mib
  result_duration: 2d
  sessions_per_node: 13
  samples: 600
  tool: s3bench

test_7:
  TEST_ID: TEST-35684
  object_size:
    start: 500Mib
    end: 1Gib
  result_duration: 2d
  sessions_per_node: 21
  samples: 700
  tool: s3bench

test_8:
  TEST_ID: TEST-35685
  object_size:
    start: 1Gib
    end: 2Gib
  result_duration: 4d
  sessions_per_node: 34
  samples: 800
  tool: s3bench

test_9:
  TEST_ID: TEST-35686
  object_size:
    start: 2Gib
    end: 5Gib
  result_duration: 5d
  sessions_per_node: 55
  samples: 900
  tool: s3bench

test_10:
  TEST_ID: TEST-35687
  object_size:
    start: 5Gib
    end: 10Gib
  result_duration: 5d
  sessions_per_node: 89
  samples: 1000
  tool: s3bench

test_11:
  TEST_ID: TEST-35688
  object_size:
    start: 10Gib
    end: 20Gib
  result_duration: 5d
  sessions_per_node: 144
  samples: 1100
  tool: s3bench

test_12:
  TEST_ID: TEST-35689
  object_size:
    start: 20Gib
    end: 50Gib
  result_duration: 5d
  sessions_per_node: 233
  samples: 1200
  tool: s3bench
