test_1:
  TEST_ID: TEST-35678
  start_range: 0Kib
  end_range: 100Kib
  result_duration: 1h
  sessions_per_node: 1
  tool: s3bench

test_2:
  TEST_ID: TEST-35679
  start_range: 100Kib
  end_range: 1Mib
  result_duration: 4h
  sessions_per_node: 2
  tool: s3bench

test_3:
  TEST_ID: TEST-35680
  start_range: 1Mib
  end_range: 10Mib
  result_duration: 1d
  sessions_per_node: 3
  tool: s3bench

test_4:
  TEST_ID: TEST-35681
  start_range: 10Mib
  end_range: 20Mib
  result_duration: 1d
  sessions_per_node: 5
  tool: s3bench

test_5:
  TEST_ID: TEST-35682
  start_range: 20Mib
  end_range: 100Mib
  result_duration: 1d
  sessions_per_node: 8
  tool: s3bench

test_6:
  TEST_ID: TEST-35683
  start_range: 100Mib
  end_range: 500Mib
  result_duration: 1d
  sessions_per_node: 13
  tool: s3bench

test_7:
  TEST_ID: TEST-35684
  start_range: 500Mib
  end_range: 1Gib
  result_duration: 1d
  sessions_per_node: 21
  tool: s3bench

test_8:
  TEST_ID: TEST-35685
  start_range: 1Gib
  end_range: 2Gib
  result_duration: 7d
  sessions_per_node: 34
  tool: s3bench

test_9:
  TEST_ID: TEST-35686
  start_range: 2Gib
  end_range: 5Gib
  result_duration: 5d
  sessions_per_node: 55
  tool: s3bench

test_10:
  TEST_ID: TEST-35687
  start_range: 5Gib
  end_range: 10Gib
  result_duration: 5d
  sessions_per_node: 89
  tool: s3bench

test_11:
  TEST_ID: TEST-35688
  start_range: 10Gib
  end_range: 20Gib
  result_duration: 5d
  sessions_per_node: 144
  tool: s3bench

test_12:
  TEST_ID: TEST-35689
  start_range: 20Gib
  end_range: 50Gib
  result_duration: 5d
  sessions_per_node: 233
  tool: s3bench
