clients: 10
samples: 1500
size: '256Mb'
loop_count: 10
delay: 30 #Before service restart
edit_deployment_delay: 120
#sizes in size_list are in Mb
size_list: [1, 2, 3, 4, 5, 6, 7]
# count to restart the rgw process
rgw_restart_cnt: 5
# count to restart for multiple process restart test cases
multi_process_restart_count: 10

#m0d restart interval for Continuous IO's test - 1hr
m0d_restart_continuous_ios_delay: 3600

test_41234:
  samples: 50

test_41235:
  samples: 10

#overwrite object test
test_41230:
  max_object_size: 512 #Mb
  overwrite_cnt: 200

test_42246:
  num_loop: 300
  clients: 2
  samples: 2

test_42247:
  samples: 50

test_41245:
  #Before and after m0d restart
  rgw_restarts: 5
  num_loop: 500
  rgw_delay_before: 120
  m0d_delay: 600
  rgw_delay_after: 600

test_42255:
  samples: 70
  num_loop: 10

#overwrite object test-rgw
test_42251:
  max_object_size: 512 #Mb
  overwrite_cnt: 200

test_42252:
  samples: 50

test_42256:
  samples: 50
