clients: 10
samples: 500
size: '128Mb'
loop_count: 10
delay: 30 #Before service restart

#sizes in size_list are in Mb
size_list: [1, 2, 3, 4, 5, 6, 7]
# count to restart the rgw process
rgw_restart_cnt: 5

test_41234:
  nsamples: 30

test_41235:
  nsamples: 10

#overwrite object test
test_41230:
  max_object_size: 512 #Mb
  overwrite_cnt: 200

test_42246:
  samples: 10
  num_loop: 300

test_42247:
  nsamples: 50

test_42248:
  nsamples: 50

test_41245:
  #Before and after m0d restart
  rgw_restarts: 5
  num_loop: 500

test_42255:
  nsamples: 70
  num_loop: 10

#overwrite object test-rgw
test_42251:
  max_object_size: 512 #Mb
  overwrite_cnt: 200

test_42252:
  nsamples: 50

test_42256:
  nsamples: 50
