FROM ghcr.io/cortx-admin/cortx-test-l1:latest

ARG GIT_USERNAME
ARG GIT_REPO
ARG GIT_ID
ARG GIT_PASSWORD
ARG GIT_BRANCH

RUN git clone --branch $GIT_BRANCH https://$GIT_ID:$GIT_PASSWORD@github.com/$GIT_USERNAME/$GIT_REPO

RUN mkdir -p /etc/ssl/stx-s3-clients/s3/
COPY ci_tools/ca.crt /etc/ssl/stx-s3-clients/s3/

RUN mkdir /root/.aws
WORKDIR /cortx-test
RUN python3.7 -m pip install awscli awscli-plugin-endpoint
RUN aws configure set plugins.endpoint awscli_plugin_endpoint
RUN aws configure set s3.endpoint_url https://s3.seagate.com
RUN aws configure set s3api.endpoint_url https://s3.seagate.com
RUN aws configure set default.ca_bundle /etc/ssl/stx-s3-clients/s3/ca.crt

RUN python3.7 -m pip install --ignore-installed -r requirements.txt

ENV AWS_ACCESS_KEY_ID=AKIATovwzXJMRbKhU0hI0szGQA
ENV AWS_SECRET_ACCESS_KEY=ly13PG6ky4lZhxJ3PvvAbjQgvWcKeRGlORLiwXaH
ENV AWS_DEFAULT_REGION=US
ENV AWS_DEFAULT_OUTPUT=json
ENV JIRA_ID=0
ENV JIRA_PASSWORD=AA
ENV TEST_PLAN_NUMBER=00000
ENV BUILD=000
ENV BUILD_TYPE=AA
ENV SETUP_TYPE=regular
ENV TARGET_NODE=ssc-vm-4308
ENV COMMENT_JIRA=00000
ENV DB_UPDATE=True
ENV SEQUENTIAL_EXECUTION=False
ENV BRANCH=stable
ENV NODES=1
ENV SERVER_TYPE=AA
ENV ENCLOSURE_TYPE=5u84
ENV SKIP_TE=None
ENV PYTHON_VAR=python3.7
ENV PLATFORM=VM_HW
ENV TEST_EXECUTION_NUMBER=000
ENV TEST_TYPES=ALL
ENV PRODUCT_FAMILY=LC
ENV HEALTH_CHECK=True
ENV USE_SSL=True
ENV CSM_CHECKS=False
ENV VALIDATE_CERTS=True
ENV DATA_INTEGRITY_CHECK=False
ENV LOG_LEVEL=10
COPY secrets.json .
