RPM_GREP_CMD = "rpm -qa | grep {}"
RPM_INSTALL_CMD = "yum install -y {0}"
LST_RPM_CMD ="rpm -qa | grep eos-prvsnr"
LST_PRVSN_DIR = "ls /opt/seagate/"
LS_CMD = "ls {}"
SYSTEM_CTL_STOP = f"systemctl stop %s"
SYSTEMCTL_START = f"systemctl start %s"
SYSTEMCTL_STATUS = f"systemctl status %s"
PKIL_CMD = "pkill {}"
CREATE_FILE = "dd if=/dev/zero of={} bs=1M count={}"