RPM_GREP_CMD = "rpm -qa | grep {}"
RPM_INSTALL_CMD = "yum install -y {0}"
LST_RPM_CMD ="rpm -qa | grep eos-prvsnr"
LST_PRVSN_DIR = "ls /opt/seagate/"
LS_CMD = "ls {}"
SYSTEM_CTL_STOP = f"systemctl stop %s"
SYSTEMCTL_START = f"systemctl start %s"
SYSTEMCTL_STATUS = f"systemctl status %s"
PKIL_CMD = "pkill {}"
CREATE_FILE = "dd if=/dev/zero of={} bs=1M count={}"
PGREP_CMD = "sudo pgrep {}"
MOTR_STATUS_CMD = "hctl status"
MERO_STOP_FIDS = "hctl mero process stop --fid {} --force"
MERO_START_FIDS = "hctl mero process start --fid {}"
NETSAT_CMD = "netstat -tnlp | grep {}"
FIREWALL_CMD = "firewall-cmd --service={} --get-ports --permanent"
CPU_USAGE_CMD = "python3 -c 'import psutil; print(psutil.cpu_times_percent(interval=1)[2])'"
MEM_USAGE_CMD = "python3 -c 'import psutil; print(psutil.virtual_memory().percent)'"
GREP_PCS_SERVICE_CMD = "pcs status | grep {}"
PCS_CLUSTER_STOP = "pcs cluster stop {}"
PCS_CLUSTER_START = "pcs cluster start {}"
PCS_RESOURCES_CLEANUP = "pcs resource cleanup {}"