apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - <IP1>-<IP1>
      - <IP2>-<IP2>
      - <IP3>-<IP3>
