log_dir: "s3bench_logs/"
go_path: "/root/go/src/"
s3bench_path: "/root/go/src/s3bench"
cmd_go: "sudo yum install -y go"
s3bench_get: "go get github.com/igneous-systems/s3bench"
s3bench_git: "git clone https://github.com/igneous-systems/s3bench.git {}"

log_format:
  format: "%(asctime)s - %(message)s"