test_22203:
  threads: 25
  rampup: 1
  loop: 10
test_22204:
  threads: 5
  rampup: 3
  loop: 10
test_22207:
  threads: 5
  rampup: 1
  loop: 10
test_22208:
  wait_for_alert: 60
  threads: 25
  rampup: 8
  loop: 10
  delta_cpu_usage: -80
  resource_type: node:os:cpu_usage
test_32547:
  threads: 25
  rampup: 1
  loop: 10
test_44256:
  threads: 25
  rampup: 1
  loop: 10
test_44257:
  threads: 5
  rampup: 2
  loop: 10
test_44782:
  request_usage: 30
  total_users: 97
  rampup: 1
  error_code: 4104
  message_id: "PermissionDenied"
  message_index: 2
