test_1120:
  users:
    - csm_admin_user
    - csm_user_manage
    - csm_user_monitor
    - s3account_user

test_1142:
  username: "dk"
  password: "dk"

test_4244:
  username_key: "user"
  password_key: "pswd"
  username: "dk"
  password: "dk"

test_4245:
  username: ""
  password: ""