test_1225:
  comment_text_admin_user: "Comment added by CSM admin user"
  comment_text_manage_user: "Comment added by CSM manage user"

test_607:
  alert_timeout: 300
  alert_type: "controller_a_fault"
  resolve_type: "controller_a_fault_resolved"
  alert_severity: "critical"
  resolve_severity: "informational"

test_608:
  alert_timeout: 300
  alert_type: "iem_test_error_alert"
  alert_severity: "error"

test_609:
  alert_timeout: 300
  alert_type: "controller_a_fault"
  resolve_type: "controller_a_fault_resolved"
  alert_severity: "critical"

test_610:
  alert_timeout: 300
  alert_type: "controller_a_fault"
  resolve_type: "controller_a_fault_resolved"
  alert_severity: "critical"
  resolve_severity: "informational"

test_611:
  alert_timeout: 300
  alert_type: "controller_a_fault"
  resolve_type: "controller_a_fault_resolved"
  alert_severity: "critical"
  resolve_severity: "informational"

test_616:
  alert_timeout: 300
  alert_type: "controller_a_fault"
  resolve_type: "controller_a_fault_resolved"

test_617:
  alert_timeout: 300
  alert_type: "controller_a_fault"
  resolve_type: "controller_a_fault_resolved"

test_618:
  alert_timeout: 300
  alert_type: "controller_a_fault"
  resolve_type: "controller_a_fault_resolved"

test_619:
  alert_timeout: 300
  alert_type: "controller_a_fault"
  resolve_type: "controller_a_fault_resolved"

test_620:
  alert_timeout: 300
  alert_type: "controller_a_fault"
  resolve_type: "controller_a_fault_resolved"

test_621:
  alert_timeout: 300
  alert_type: "controller_a_fault"
  resolve_type: "controller_a_fault_resolved"
test_1039:
  comment_text: "Comment by S3 user"
