test_xxxxx:
  active_users_quota: 50
  tmp_users_password: "Seagate@123"
test_yyyyy:
  sessions_quota: 10
  tmp_user_password: "Seagate@123"
test_zzzzz:
  requests_quota: 200
  api_endpoint: "/api/v2/csm/users"
