services:
  authserver: "s3authserver"
  s3instances:
    - "s3server-c1-*"
    - "s3server-c2-*"
  s3bgcons: "s3backgroundconsumer"
  s3backprod: "s3backgroundproducer"
  ldap_service: "slapd.service"
  csm_recource_group:
    - "kibana-vip"
    - "kibana"
    - "csm_web"
    - "csm_agent"

s3:
  file_path: "/tmp/dest-obj.txt"

s3bench:
  url: "https://s3.seagate.com"
  bucket_name: "dstrctv-bkt-mnf1"
  numClients: 300
  numSamples: 800
  objectNamePrefix: "dstrctv-obj"
  objectSize: 2147483648
  skipCleanup: False
  verbose: True

common_sleep_time: 60

locust:
  user_count: 2
  hatch_rate: 2
  duration: 15m
  log_path: "locust_log"
  success_msg:
    - "Buckets Created:"
    - "has been downloaded successfully at mentioned filepath"
    - "Deleted bucket :"
# Fan fault: alerts string form RAS & CSM.
fan_fault:
  generate_fault: "down"
  resolve_fault: "up"
  resource_id: "Fan Module 1"
  resource_id_string_rmq : '"resource_id": "Fan Module 1"'
  resource_id_string_csm : '"resource_id":"Fan Module 1"'
  alert_fault: "fault"
  "alert_type": "fault"
  alert_fault_resolved: "fault_resolved"
  resource_type: "enclosure:fru:fan"
  error_msg: "Failed to put management network port"
  statsd_wait: 120


# Following dict indicates: Key from console output amd values from parsed output xml.
# User can add more pair as per need and scope.
show_volumes:
  pool: "storage-pool-name"
  name: "volume-name"
  total_size: "total-size"
  alloc_size: "allocated-size"
  type: "storage-type"
  health: "health"
  reason: "health-reason"
  action: "health-recommendation"

show_expander_status:
  encl: "enclosure-id"
  ctlr: "controller"
  phy: "wide-port-index"
  type: "type"
  status: "status"
  disabled: "elem-disabled"
  reason: "elem-reason"

show_disk_groups:
  name: "name"
  size: "size"
  created: "create-date"
  job: "current-job"
  job_percent: "current-job-numeric"
  raidtype: "raidtype"
  health: "health"
  reason: "health-reason"
  action: "health-recommendation"

show_disks:
  pool: "durable-id"
  location: "location"
  serial_number: "serial-number"
  vendor: "vendor"
  rev: "revision"
  description: "description"
  usage: "usage"
  size: "size"
  disk_group: "disk-group"
  tier: "storage-tier"
  health: "health"
  reason: "health-reason"
  action: "health-recommendation"

debug: False

s3bench_min_objsize:
  url: "https://s3.seagate.com"
  bucket_name: "dstrctv-bkt-mnf1"
  numClients: 300
  numSamples: 800
  objectNamePrefix: "dstrctv-obj"
  objectSize: 524288000
  skipCleanup: False
  verbose: True
