# Common configs
delay_60sec: 60
sshWaitTime: 120

dataPathServices:
  - "s3authserver"
management_services:
  - "kibana-vip"
  - "kibana"
  - "csm-web"
  - "csm-agent"
  - "uds"
meroServices:
  - "-confd-c"
  - "-ios-c"
haproxy_service:
  - "haproxy-c"
audit_service: "auditd.service"
statsd_service: "statsd"
prod_type: "k8s"
prod_family: "LC"

product_type: "k8s"
product_family: "LC"
s3_engine: 1
dtm0_disabled: True
