workloads_distribution:
  0Kb: 2
  1Kb: 24.79
  10Kb: 18.84
  100Kb: 17.87
  1Mb: 18.2
  10Mb: 16.7
  100Mb: 1.56
  1Gb: 0.03
  2Gb: 0.01
sessions_per_node_vm: 20
sessions_per_node_hw: 150

happy_path_duration_days: 30
degraded_path_durations_days: 7

test_40172:
  bucket_creation_healthy_mode: True

nearfull_storage_percentage: 95

test_40042:
  write_percent_per_iter: 30
  delete_percent_per_iter: 15
  max_cluster_capacity_percent: 95

test_40174:
  write_percent_per_iter: 40
  delete_percent_per_iter: 20
  max_cluster_capacity_percent: 95