prereq:
  count: 2
  os_release: "CentOS Linux release 7.8.2003 (Core)"
  kernel: "3.10.0-1127.el7.x86_64"
deploy:
  sleep_time: 10
  success_msg: "SUCCESS"
system:
  offline: "offline"
  stopped: "Stopped"


