enclosure_id: "1234"
sspl_exch: "sspl-out"
sspl_key: "sensor-key"
sspl_user: "sspluser"
sspl_pass: "sspl4ever"

ras_sspl_alert:
  ees_server_path: "/"
  disk_usage_val: 5
  wait_time: 5
  create_dir_cmd: "mkdir -p {}"
  file:
    sspl_conf_filename: "/etc/sspl.conf"
    sspl_cfg_temp: "/tmp/sspl.conf"
    original_sspl_conf: "/etc/sspl_original.conf"
    alert_log_file: "/root/rabbitmq_alert.log"
    extracted_alert_file: "/root/extracted_alert.log"
    encrypter_local_path: "/root/encryptor_updated.py"
    temp_txt_file: "temp.txt"
    telnet_xml: "/root/telnet.xml"
    sspl_log_file: "/root/sspl_log.txt"
    screen_log: "/root/screenlog.0"
    disk_usage_temp_file: "/root/disk_usage_temp.txt"
    lsscsi_file: "/root/lsscsi.txt"
    local_path: "/tmp/rabbitmq_alert.log"
    selinux_status: "/root/selinux_status.log"

  sspl_config:
    sspl_section: "NODEDATAMSGHANDLER"
    sspl_du_key: "disk_usage_threshold"
    sspl_du_dval: "80"
    server_du_path: "/"
    sspl_trans_intv_key: "transmit_interval"
    sspl_trans_intv_dval: 300
    sspl_trans_intv_val: 10
    sspl_log_level_key: "log_level"
    sspl_log_level_val: "WARNING"
    sspl_log_dval: "INFO"
  ldap_user: "sgiamadmin"
  ldap_pwd: "ldapadmin"
  sleep_val: 120
  sspl_timeout: 190
  os_lvl_monitor_timeouts:
    alert_timeout: 5
    intrmdt_state: 200
  ipmitool_sdr_cmd: "ipmitool sdr list"
  sspl_exch: "sspl-out"
  sspl_key: "sensor-key"
  service:
    sspl_service: "sspl-ll"
    kafka_service: "kafka"
    csm_web: "csm_web"
    csm_agent: "csm_agent"
  sspl_resource_id: "sspl-ll-clone"
  mc_debug_port: 7900
  telnet_sleep_val: 120
  max_wait_time: 320
  default_cpu_usage: 80
  csm_error_msg: "Failed to get alerts using CSM REST API"
  csm_alert_gen_delay: 60
  default_mem_usage: 80
  start_msg_bus: False
  selinux_key: "SELINUX"
  selinux_disabled: "disabled"
  selinux_enforced: "enforcing"
  local_selinux_path: "selinux_config"
  reboot_delay: 720
  one_min_delay: 60
  disk_clean_time: 120

mdstat_remote_path: "/proc/mdstat"
mdstat_local_path: "mdstat"
mdadm_conf_path: "/etc/mdadm.conf"
mdadm_conf_local_path: "mdadm.conf"

raid_param:
  csm_error_msg: "Failed to get alerts using CSM REST API"
  stop_operation: "stop"
  assemble_operation: "assemble"
  fail_operation: "fail_disk"
  remove_operation: "remove_disk"
  add_operation: "add_disk"
  csm_alert_reflection_time: 60
  md0_path: "/dev/md0"
  disk_path: "/dev/{}"
  resync_delay: 300

nw_fault_params:
  min_wait_time: 180
  max_wait_time: 300
  min_wait_after_io: 160