alert_types:
  fault: "fault"
  resolved: "fault_resolved"
  missing: "missing"
  insertion: "insertion"
  get: "get"

network_interfaces:
  VM:
    MGMT: "eth0"
    PUBLIC_DATA: "eth1"
    PRIVATE_DATA: "eth3"
  HW:
    #Check network interface names when R2 HW is available
    MGMT: "eno1"
    PUBLIC_DATA: "enp175s0f0"
    PRIVATE_DATA: "enp175s0f1"

common_cfg:
  faulty_cpu_id:
    - 0
    - 1

test_3005:
  alert: True
  du_val: 8
  alert_type: "fault_resolved"
  resource_type: "node:os:disk_space"

test_3006:
  alert: False
  resource_type: "node:os:disk_space"
  alert_fault:
    du_val: 8
    alert_type: "fault"
  alert_fault_resolved:
    du_val: 8
    alert_type: "fault_resolved"

test_3104:
  buffer_sz: 100000
  check_time_sspl: "systemd-analyze blame | grep {}"
  sspl_time: 2
  time_cmd: 3

test_3161:
  buffer_sz: 100000
  ipmitool_event:
    - "ipmitool event {} ucr"
    - "ipmitool event {} lcr"
    - "ipmitool event {} lnr"
  resource_type: "node:fru:fan"
  alert_type: "fault"
  wait_time: 5
  operations:
    - "ucr"
    - "lcr"
    - "lnr"

test_3280:
  buffer_sz: 100000
  ipmitool_event: "ipmitool event {} lcr"
  op: "lcr"
  alert_type: "fault"
  resource_type: "node:fru:fan"
  wait_time: 10

test_1299:
  batch_count: 6
  buffer_sz: 100000
  ipmitool_event: 'ipmitool event "{}" lcr'
  usage_pattern: "Percent Used"
  wait_time: 1
  range_max: 90

test_4332:
  pos: left
  fru: psu
  type_fault: e
  fault_resolved: r
  ctrl_name: a
  enclId : 0
  alert_type: "fault"
  resource_type: "enclosure:fru:psu"

test_4362:
  pos: a
  fru: ctrl
  type_fault: e
  fault_resolved: r
  ctrl_name: a
  enclId : 0
  alert_type: "fault_resolved"
  resource_type: "enclosure:fru:controller"
  err_msg: "Couldn't connect to telnet port 7900. Please try on other controller (Generating Fault) - {}"

test_4335:
  fru: psu
  type_fault: e
  fault_resolved: r
  ctrl_name: a
  enclId : 0
  pos : left
  alert_type: "fault_resolved"
  resource_type: "enclosure:fru:psu"

test_4361:
  fru: ctrl
  type_fault: e
  fault_resolved: r
  ctrl_name: a
  enclId : 0
  pos : a
  alert_type: "fault"
  resource_type: "enclosure:fru:controller"

test_6916:
  key: "log_level"
  log_level_val: "WARNING"

test_4349:
  port_name:
    - "primary_controller_port"
    - "secondary_controller_port"
  port_number: 5100
  test_sspl_file: "/home/sspl_4349.txt"

test_3424:
  rsyslog_service: "rsyslog"
  logger_cmd: "logger -i -p local3.err IEC: BO00100101000:Error in connecting to controller"
  alert_type: "get"
  resource_type: "iem"
  description: "Error in connecting to controller"

test_6592:
  key: "log_level"
  log_level_val:
    - "WARNING"
    - "ERROR"
  test_sspl_file: "/home/sspl_6592.txt"

test_157:
  encl: 0
  ctrl: A
  operation_fault: "Disabled"
  degraded_phy_status:
    - "Degraded"
    - "Fault"
  operation_fault_resolved: "Enabled"
  ok_phy_status: "OK"
  alert_type: "fault"
  resource_type: "enclosure:fru:disk"
  retry: 2

test_158:
  encl: 0
  ctrl: A
  operation_fault: "Disabled"
  degraded_phy_status:
    - "Degraded"
    - "Fault"
  operation_fault_resolved: "Enabled"
  ok_phy_status: "OK"
  alert_type: "fault_resolved"
  resource_type: "enclosure:fru:disk"
  cat_cmd: "cat {}"
  retry: 2

test_6335:
  buf_sz: 100
  file_name:
    - "components"
    - "s3"
    - "motr"
    - "auth"
    - "csm"
  err_msg: "Error in fetching user"
  alert_type: "get"
  cat_cmd: "cat {}"
  ied_code_initial: "IEC: BS{}:{}"
  wait_time: 240
  alert_wait: 2
  resource_type: "iem"

# Test parameters for TEST-1648 and TEST-1783 ran in test_sspl_secondary.py
test_1648:
  buffer_sz: 100000
  ipmitool_event: "ipmitool event {} {}"
  op: lnr
  resource_type: "node:fru:fan"
  alert_type: "fault"
  wait_time: 60

test_5924:
  fields:
    - "user"
    - "password"

test_4354:
  delta_cpu_usage: -0.3
  alert_type: "fault"
  resource_type: "node:os:cpu"

test_1645:
  buffer_sz: 100000
  op: lnr
  resource_type: "node:fru:fan"
  alert_type: "fault"
  alert_delay: 60
  reboot_delay: 600

test_4355:
  delta_mem_usage: -3
  alert_type: "fault"
  resource_type: "node:os:memory_usage"

test_5345:
  alert_fault: "fault"
  alert_fault_resolved: "fault_resolved"
  resource_type: "node:os:raid_data"
  csm_error_msg: "Failed to get alerts using CSM REST API"

test_5342:
  alert_fault: "fault"
  resource_type: "node:os:raid_data"
  alert_missing: "missing"

test_4785:
  alert_fault: "fault"
  resource_type: "node:os:raid_data"

test_5343:
  alert_fault: "fault"
  resource_type: "node:os:raid_data"
  alert_missing: "missing"
  alert_insertion: "insertion"
  alert_fault_resolved: "fault_resolved"

test_22060:
  disk_group: "dg00"
  resource_type: "node:enclosure:disk-group"
  enclid: 0
  ctrl_name: ['A', 'B']
  operation_fault: "Disabled"
  operation_fault_resolved: "Enabled"
  csm_error_msg: "Failed to get alerts using CSM REST API"

nw_port_fault:
  resource_id_monitor : '"resource_id": "{}"'
  resource_id_csm : '"resource_id":"{}"'
  resource_type: "node:interface:nw"
  error_msg: "Failed to put management network port in"

nw_cable_fault:
  disconnect: 0
  connect: 1
  resource_id_monitor : '"resource_id": "{}"'
  resource_id_csm : '"resource_id":"{}"'
  resource_type: "node:interface:nw:cable"
  error_msg: "Failed to {} management network cable"

test_21587:
  delta_cpu_usage: -5
  resource_type: "node:os:cpu_usage"

test_21588:
  delta_mem_usage: -5
  resource_type: "node:os:memory_usage"

test_21586:
  delta_disk_usage: -5
  resource_type: "node:os:disk_space"

test_23045:
  resource_type: "node:os:cpu:core"
  faulty_cpu_id:
    - 0
    - 1

test_22787:
  resource_type: "node:os:cpu_usage"
  interval: 30

test_22786:
  resource_type: "node:os:memory_usage"
  vm_count: 1
  memory_size: "5G"
  timespan: "10m"
  buffer: 10

TEST-23606:
  resource_type: "node:os:disk"
  csm_error_msg: "Failed to get OS disk alerts using CSM REST API"

test_23715:
  md_device: "/dev/md2"
  resource_type: "node:os:raid_data"
  csm_error_msg: "Failed to get alerts using CSM REST API"

test_23723:
  resource_type: "node:os:raid_data"

test_22891:
  resource_disk_space: "node:os:disk_space"
  resource_cpu_usage: "node:os:cpu_usagee"
  resource_memory_usage: "node:os:memory_usage"
  resource_cpu_fault: "node:os:cpu:core"
  vm_count: 1
  memory_size: "5G"
  timespan: "10m"
  interval: 30
