#TODO - need to revisit all the paths and IPs mentioned in this file

logserver: "10.237.65.125"
logserver_path: "/root/mahesh/temp"
logserver_username: "root"
logserver_password: "seagate"
log_destination: "/root/mahesh/temp"

file_exention : ".log"
file_list:
  - 's3'
  - 'motr'
  - 'ras'
  - 'ha'
  - 'prov'

node_username: "root"
node_password: "seagate"
node_list:
  - 'node1'
  - 'node2'
  - 'node3'
  - 'node4'

file_path_dict:
  s3: "/home/s3path"
  motr: "/root/mahesh"
  ras: "/home/raspath"
  ha: "/home/hapath"
  prov: "/home/provpath"

node_ip_dict:
  node1: "10.237.65.202"
  node2: "10.237.65.160"
  