#!/usr/bin/expect -f

set timeout 20
set ip [lindex $argv 0]
set user [lindex $argv 1]
set password [lindex $argv 2]
set port [lindex $argv 3]
set op [lindex $argv 4]

spawn telnet $ip
expect "'^]'."
#sleep 1;
send "\r";
#sleep 1;
expect "Username:"
send "$user\r"
expect "Password:"
send "$password\r";

#interact
expect "[My PDU] >"
send "power outlets $port off /y\r";
sleep 10
expect "[My PDU] >"
send "power outlets $port on /y\r";
expect "[My PDU] >"
send "exit\r";
