test_1:
  TEST_ID:
  start_range: 0Kb
  end_range: 100Kb
  start_time: 0
  result_duration: 1hr
  sessions_per_node: 1

test_2:
  TEST_ID:
  start_range: 100Kb
  end_range: 1Mb
  start_time: 1hr
  result_duration: 4hr
  sessions_per_node: 2

test_3:
  TEST_ID:
  start_range: 1Mb
  end_range: 10Mb
  start_time: 5hr
  result_duration: 1D
  sessions_per_node: 3

test_4:
  TEST_ID:
  start_range: 10Mb
  end_range: 20Mb
  start_time: 30hr
  result_duration: 1D
  sessions_per_node: 5

test_5:
  TEST_ID:
  start_range: 20Mb
  end_range: 100Mb
  start_time: 54hr
  result_duration: 1D
  sessions_per_node: 8

test_6:
  TEST_ID:
  start_range: 100Mb
  end_range: 500Mb
  start_time: 78hr
  result_duration: 2D
  sessions_per_node: 13

test_7:
  TEST_ID:
  start_range: 500Mb
  end_range: 1Gb
  start_time: 126hr
  result_duration: 2D
  sessions_per_node: 21

test_8:
  TEST_ID:
  start_range: 1Gb
  end_range: 2Gb
  start_time: 174hr
  result_duration: 7D
  sessions_per_node: 34

test_9:
  TEST_ID:
  start_range: 2Gb
  end_range: 5Gb
  start_time: 342hr
  result_duration: 5D
  sessions_per_node: 55

test_10:
  TEST_ID:
  start_range: 5Gb
  end_range: 10Gb
  start_time: 462hr
  result_duration: 5D
  sessions_per_node: 89

test_11:
  TEST_ID:
  start_range: 10Gb
  end_range: 20Gb
  start_time: 582hr
  result_duration: 5D
  sessions_per_node: 144

test_12:
  TEST_ID:
  start_range: 20Gb
  end_range: 50Gb
  start_time: 702hr
  result_duration: 5D
  sessions_per_node: 233