common_cfg:
  s3fs_tool: "s3fs"
  success_msg: "Bucket '{}/' create"
  bucket_name: "s3fsbucket-{}"
  bkt_name_prefix: "s3fsbucket-"
  passwd_file: "-o passwd_file=/etc/passwd-s3fs"
  url: "-o url=https://s3.seagate.com/"
  path_style: "-o use_path_request_style"
  dbglevel: "-o dbglevel=info"
  make_dir_cmd: "mkdir"
  dir_name: "/mnt/s3fstest{}"
  new_dir_name: "s3fstest1{}"
  dir_to_rm: "/mnt/s3fstest"
  df_cmd: "df -h"
  rm_file_cmd: "rm -rf"
  unmount_cmd: "umount"
  dd_cmd: "dd"
  input_file: "if=/dev/zero of={}"
  count: "count={}"
  block_size: "bs={}"
  create_file_cmd: "touch"
  file_name: "file1{}"
  ls_mnt_dir_cmd: "ls"
  obj_name_prefix: "file1"

