blackbox_aws_cli:
  bucket_name: "blkboxawsclibkt{0}"
  bkt_name_prefix: "blkboxawsclibkt"
  cr_bkt_cmd: "aws s3 mb s3://{0}"
  del_bkt_cmd: "aws s3 rb s3://{0}"
  del_bkt_f_cmd: "aws s3 rb s3://{0} --force"
  put_obj_cmd: "aws s3 cp {0} s3://{1}/{2}"
  file_path: "/home/"
  file_name: "blkbox_obj{0}.txt"
  file_mb_count: 1

test_2329:
  bucket_name_1: "blkboxawsclibkt-23291{0}"
  bucket_name_2: "blkboxawsclibkt-23292{0}"
  cr_two_bkts_cmd: "aws s3 mb s3://{0} s3://{1}"

test_2330:
  ls_bkt_cmd: "aws s3 ls"

test_2331:
  bucket_name: "blkboxawsclibkt2331{0}"
  no_of_buckets: 1000
  err_message: "Failed to create {0} buckets"

test_2332:
  err_message: "Bucket was not deleted"

test_2333:
  no_of_objects: 3
  err_message: "BucketNotEmpty"

test_2334:
  head_bkt_cmd: "aws s3api head-bucket --bucket {0}"

test_2335:
  bkt_loc_cmd: "aws s3api get-bucket-location --bucket {0}"
  bkt_location: "US"

test_2336:
  err_message: "BucketAlreadyOwnedByYou"

test_2337:
  no_of_objects: 3
  err_message: "Bucket is not deleted"

test_2338:
  no_of_objects: 4
  ls_obj_cmd: "aws s3 ls s3://{0}"

test_2339:
  obj_id: 1
  rm_obj_cmd: "aws s3 rm s3://{0}/{1}"

test_2340:
  no_of_objects: 3
  rm_mul_obj_cmd: "aws s3 rm s3://{0}/ --recursive --exclude '*' "
  include_flg: "--include "
  no_obj_to_del: 2
  err_message: "{0} object was not deleted"

test_2341:
  no_of_objects: 3
  rm_all_obj_cmd: "aws s3 rm --recursive s3://{0}"

test_2342:
  mp_obj: "/home/blkbox_mp_obj"
  mp_obj_size: 10000
  no_of_parts: 10
  cr_mu_cmd: "aws s3api create-multipart-upload --bucket {0} --key {1}"
  ls_mu_cmd: "aws s3api list-multipart-uploads --bucket {0}"
  up_parts_cmd: "aws s3api upload-part --bucket {0} --key {1} --part-number {2} --body {3} --upload-id {4}"
  ls_parts_cmd: "aws s3api list-parts --bucket {0} --key {1} --upload-id {2}"
  cmp_mpu_cmd: "aws s3api complete-multipart-upload --multipart-upload file://{0} --bucket {1} --key {2} --upload-id {3}"
  json_file: "parts.json"

test_2343:
  obj_id: 1

test_2344:
  obj_id: 1
  get_obj_cmd: "aws s3 cp s3://{0}/{1} {2}"
  downloaded_file: "/home/get_blkbox_obj.txt"
  err_message: "Download was not successful"


