acc_user_mng:
  account_name: "seagate_account_1nm"
  email_id: "seagate_account_1nm@seagate.com"
  password: "seagate"
  password_reset: False
  user_name: "seagate_user_9"
  test_file_path: "/home/testfile"
common_cfg:
  s3cmd_tool: "s3cmd"
  success_msg: "Bucket '{}/' create"
  bkt_prefix: "s3cmd-test-bucket"
  make_bucket : "mb"
  put_bucket: "put"
  remove_bucket : "rb"
  s3cmd_format_keys: "--access-key {} --secret-key {}"
  bkt_path_format: "s3://{}"
  file_path: "/home/s3cmdtestfile.txt"
  file_size: 10
  root_path: "/home/"
  file_format: ".txt"
  bucket_name: "s3cmdbucket-nm{}"
  bucket_name_prefix: "s3cmdbucket-nm"
  file_name: "s3cmdtestfile{}.txt"
  file_prefix: "s3cmdtestfile"
  list_bkt: "s3cmd ls"
  count_bkt: 100 #this count is not fixed.This may change in future.
  warning_msg: "WARNING:"
  upload_msg: "done"
s3cmd_bucket:
  bkt_name_prefix: "s3cmdbkt"
  file_path: "/home/s3cmd_blackbox.txt"
  file_size: 10
test_2309:
  success_msg: "Bucket '{}/' create"
test_2326:
  success_msg: "Bucket '{}/' create"
  error_msg: "BucketAlreadyOwnedByYou"
test_2313:
  success_msg_del: "Bucket '{}/' remove"
  success_msg_crt: "Bucket '{}/' create"
  remove_bucket : "rb"
test_2312:
  success_msg_del: "Bucket '{}/' remove"
  success_msg_crt: "Bucket '{}/' create"
  remove_bucket : "rb"
test_2311:
  success_msg: "Bucket '{}/' create"
test_2310:
  success_msg: "Bucket '{}/' create"
  list_bucket: "ls"
test_2308:
  success_msg: "Bucket '{}/' create"
  list_bucket: "ls"
test_2316:
  success_msg: "Bucket '{}/' create"
  file_creation: "echo “Hello World2316” > {}"
test_2314:
  file_creation: "echo “Hello World2314” > {}"
  error_msg: "BucketNotEmpty"
test_2320:
  success_msg: "Bucket '{}/' create"
  file_creation: "echo “Hello World2320” > {}"
  del_obj: "del"
  delete_msg: "delete: '{}'"
test_2321:
  success_msg: "Bucket '{}/' create"
  file_creation: "echo “Hello World2321” > {}"
  del_obj: "del"
  delete_msg: "delete: '{}'"
test_2317:
  success_msg: "Bucket '{}/' create"
  file_creation: "echo “Hello World23186” > {}"
  list_bucket: "ls"

test_2322:
  success_msg: "Bucket '{}/' create"
  file_creation: "echo “Hello World2322” > {}"
  list_bucket: "ls"
  rm_bkt: "rm"
  force: "--force"
  recursive: "--recursive"
  delete_msg: "delete: '{}'"

test_2327:
  info: "info"
  success_msg2: "Location:"
  success_msg3: "Payer:"
  success_msg4: "Expiration Rule:"
  success_msg5: "Policy:"
  success_msg6: "CORS:"
  success_msg7: "ACL:"

test_2319:
  success_msg: "Bucket '{}/' create"
  file_creation: "echo “Hello World2319” > {}"
  get: "get"
  force: "--force"
  success_msg2: "download: '{}'"
  success_msg3: "done"

test_2315:
  success_msg: "Bucket '{}/' create"
  file_creation: "echo “Hello World2315” > {}"
  success_msg_del: "Bucket '{}/' remove"
  list_bucket: "ls"
  rm_bkt: "rb"
  recursive: "--recursive"
  error_msg: "NoSuchBucket"
  success_msg2: "WARNING"

test_2318:
  success_msg: "Bucket '{}/' create"
  file_creation: "echo “Hello World23186” > {}"
  list_all_buckets: "la"
