S3bench:
  object_size:
    - '4Kb'
    - '100Kb'
    - '256Kb'
    - '1Mb'
    - '5Mb'
    - '16Mb'
    - '36Mb'
    - '64Mb'
    - '128Mb'
    - '256Mb'
  meta_data:
    - '1Kb'

Hsbench:
  object_size:
    - '4Kb'
    - '100Kb'
    - '256Kb'
    - '1Mb'
    - '5Mb'
    - '16Mb'
    - '36Mb'
    - '64Mb'
    - '128Mb'
    - '256Mb'
  workload-1:
    sessions: 100
    buckets: 1
  
  workload-2:
    sessions: 100
    buckets: 10

  workload-3:
    sessions: 100
    buckets: 50
  
  modes:
    2: BINIT
    3: PUT
    4: LIST
    5: GET
    6: DEL
    7: BCLR
    8: BDEL

Cosbench:
  object_size:
    - '4Kb'
    - '100Kb'
    - '256Kb'
    - '1Mb'
    - '5Mb'
    - '16Mb'
    - '36Mb'
    - '64Mb'
    - '128Mb'
    - '256Mb'
  workload-1:
    sessions: 100
    buckets: 1
  
  workload-2:
    sessions: 100
    buckets: 10

  workload-3:
    sessions: 100
    buckets: 50
