limits:
  volume_pattern: "SEAGATE"
  total_usage_limit: 214748364800
  total_per_limit: 80

serviceinfo:

  services:
    - statsd
    - elasticsearch
    - csm_agent
    - csm_web
    - hare-consul-agent
    - hare-hax
    - m0d
    - motr-kernel
    - salt-master
    - salt-minion
    - s3server
    - haproxy
    - s3authserver
    - rabbitmq-server
    - sspl-ll

logs:
  consul:
    - "/var/log/hare/consul-watch-service.log"
    - "/var/log/hare/consul-elect-rc-leader.log"
    - "/var/log/hare/consul-proto-rc.log"
    - "/var/log/hare/consul-watch-handler.log"

  elasticsearch:
    - "/var/log/elasticsearch/elasticsearch_cluster.log"

  csm_agent:
    - "/var/log/seagate/csm/csm_agent.log"

  csm_cli:
    - "/var/log/seagate/csm/csm_cli.log"

  csm_web_server:
    - "/var/log/seagate/csm/csm_middleware.log"

  ha_lib:
    - "/var/log/seagate/cortx/ha/cortxha.log"
    - "/var/log/seagate/cortx/ha/resource_agent.log"
    - "/var/log/seagate/cortx/ha/ha_setup.log"

  hax: "/var/log/messages"
  motr:
    - "/var/mero"
    - "/var/motr"

  os:
    - "/var/log/crash"
    - "/var/log/messages"
    - "/var/log/secure"
    - "/var/log/dmesg"
  provisioner:
    - "/var/log/seagate/provisioner"

  s3:
    - "/var/log/seagate/s3/"
    - "/var/log/seagate/s3/audit/audit.log"

  haproxy: "/var/log/haproxy"
  s3auth: "/var/log/seagate/auth/server/app.log"
  ldap:
    - "/var/log/slapd.log"

  rabbitmq:
    - "/var/log/rabbitmq"
  sspl:
    - "/var/log/cortx/sspl"

pcs_status_cmd: "pcs status"
# prefer DNS name
hosts:
  - # number of nodes
  - # 1
  - # 2
  - # 3


host_domain: colo.seagate.com
username: root
password: c2VhZ2F0ZQ==
interval: 300

# hosts in password should be same as that in hosts List
passwords:
  10.237.66.55: seagate
  10.237.65.157: seagate
  sm7-r18.pun.seagate.com: seagate1
  sm8-r18.pun.seagate.com: seagate1

smtp:
  to_list: user1@testmail.com,user2@testmail.com
  from_list: user1@testmail.com
  smtpserver: 10.237.65.183
  port: 25
  passwd: c2VhZ2F0ZQ==

# One of INFO, DEBUG, ERROR
logging_Level: INFO
retries: 60
