system_limit_common:
  bucket_prefix: "test-bucket"
  iam_user_prefix: "testiamuser"
  new_password: "cOPLLtFurVdnbaqe7w+D0fMKp1Mqs/wlVM/HUxQmRSs="

test_13693:
  csm_count: 0
  s3_count: 1000
  iam_count: 1
  bucket_count: 1

test_16009:
  csm_count: 0
  s3_count: 1
  iam_count: 1000
  bucket_count: 50

test_16908:
  csm_count: 0
  s3_count: 1
  iam_count: 5
  bucket_count: 1000

test_16909:
  csm_count: 0
  s3_count: 100
  iam_count: 1
  bucket_count: 100

test_16910:
  csm_count: 99
  s3_count: 0
  iam_count: 0
  bucket_count: 0

test_16911:
  csm_count: 99
  s3_count: 0
  iam_count: 0
  bucket_count: 0

test_20274:
  list_multipart_uploads_limit: 1000

test_20271:
  metadata_limit: 2048  # user-defined metadata is limited to 2 KB from AWS
